// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { CustomType } from "drizzle-zero";
import type * as drizzleSchema from "../../db/src/schema/index";

const accountTable = {
  name: "account",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    accountId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "account_id",
    },
    providerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    accessToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "access_token",
    },
    refreshToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "refresh_token",
    },
    idToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "id_token",
    },
    accessTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "access_token_expires_at",
    },
    refreshTokenExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refresh_token_expires_at",
    },
    scope: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    password: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const apikeyTable = {
  name: "apikey",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    start: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    prefix: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    refillInterval: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refill_interval",
    },
    refillAmount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "refill_amount",
    },
    lastRefillAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_refill_at",
    },
    enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    rateLimitEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "rate_limit_enabled",
    },
    rateLimitTimeWindow: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "rate_limit_time_window",
    },
    rateLimitMax: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "rate_limit_max",
    },
    requestCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "request_count",
    },
    remaining: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    lastRequest: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_request",
    },
    expiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    permissions: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const auditLogTable = {
  name: "auditLog",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    action: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    entityType: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "entity_type",
    },
    entityId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "entity_id",
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "auditLog",
        "metadata"
      >,
    },
    ipAddress: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ip_address",
    },
    userAgent: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_agent",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "audit_log",
} as const;
const backupTable = {
  name: "backup",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "pending"
        | "running"
        | "completed"
        | "failed",
    },
    storageKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "storage_key",
    },
    size: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    checksum: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    startedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "started_at",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "completed_at",
    },
    expiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    errorMessage: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "error_message",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const backupScheduleTable = {
  name: "backupSchedule",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    cronExpression: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "cron_expression",
    },
    enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    retentionCount: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "retention_count",
    },
    retentionDays: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "retention_days",
    },
    retentionMaxSizeGb: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "retention_max_size_gb",
    },
    s3Bucket: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "s3_bucket",
    },
    s3Region: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "s3_region",
    },
    s3Endpoint: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "s3_endpoint",
    },
    s3AccessKeyRef: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "s3_access_key_ref",
    },
    s3SecretKeyRef: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "s3_secret_key_ref",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "backup_schedule",
} as const;
const caddyInstanceTable = {
  name: "caddyInstance",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    serverId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "server_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "stopped"
        | "running"
        | "error"
        | "not_installed"
        | "initializing",
      serverName: "caddy_status",
    },
    version: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    acmeEmail: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "acme_email",
    },
    lastHealthCheckAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_health_check_at",
    },
    errorMessage: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "error_message",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "caddy_instance",
} as const;
const configFileTable = {
  name: "configFile",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    filename: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    content: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    mountPath: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "mount_path",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "config_file",
} as const;
const containerRegistryTable = {
  name: "containerRegistry",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    url: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    username: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    passwordSecretRefId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "password_secret_ref_id",
    },
    isDefault: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_default",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "container_registry",
} as const;
const customDomainTable = {
  name: "customDomain",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    domain: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    verified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    verificationToken: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "verification_token",
    },
    sslStatus: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "pending"
        | "failed"
        | "active"
        | "expired",
      serverName: "ssl_status",
    },
    sslExpiresAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ssl_expires_at",
    },
    redirectRules: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        source: string;
        target: string;
        statusCode: 301 | 302;
        type: "www" | "custom";
      }[],
      serverName: "redirect_rules",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "custom_domain",
} as const;
const databaseConfigTable = {
  name: "databaseConfig",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    databaseType: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "postgresql"
        | "mysql"
        | "mariadb"
        | "mongodb"
        | "redis"
        | "keydb"
        | "dragonfly"
        | "clickhouse",
      serverName: "database_type",
    },
    image: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    databaseName: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "database_name",
    },
    databaseUser: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "database_user",
    },
    externalPort: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "external_port",
    },
    customConfig: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "custom_config",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "database_config",
} as const;
const deploymentTable = {
  name: "deployment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    environmentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "environment_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "deploying"
        | "failed"
        | "queued"
        | "building"
        | "verifying"
        | "live"
        | "canceled"
        | "rolled_back",
    },
    source: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "api"
        | "git_push"
        | "manual"
        | "rollback"
        | "preview"
        | "config_change",
    },
    gitRef: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "git_ref",
    },
    gitCommitSha: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "git_commit_sha",
    },
    gitCommitMessage: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "git_commit_message",
    },
    builder: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "nixpacks"
        | "dockerfile"
        | "buildpack"
        | "railpack",
    },
    imageTag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "image_tag",
    },
    previousImageTag: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "previous_image_tag",
    },
    startedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "started_at",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "completed_at",
    },
    duration: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    triggeredBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "triggered_by",
    },
    idempotencyKey: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "idempotency_key",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const deploymentEventTable = {
  name: "deploymentEvent",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    deploymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "deployment_id",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "deploying"
        | "failed"
        | "queued"
        | "building"
        | "verifying"
        | "live"
        | "canceled"
        | "rolled_back",
    },
    previousStatus: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "deploying"
        | "failed"
        | "queued"
        | "building"
        | "verifying"
        | "live"
        | "canceled"
        | "rolled_back",
      serverName: "previous_status",
    },
    actor: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    reason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "deploymentEvent",
        "metadata"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "deployment_event",
} as const;
const deploymentSecretSnapshotTable = {
  name: "deploymentSecretSnapshot",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    deploymentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "deployment_id",
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    entriesJson: {
      type: "json",
      optional: true,
      customType: null as unknown as {
        key: string;
        variableId: string;
        secretReferenceId: string | null;
        providerVersion: string | null;
        digest: string;
      }[],
      serverName: "entries_json",
    },
    snapshotHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "snapshot_hash",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "deployment_secret_snapshot",
} as const;
const deviceCodeTable = {
  name: "deviceCode",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    deviceCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "device_code",
    },
    userCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_code",
    },
    userId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    status: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    lastPolledAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_polled_at",
    },
    pollingInterval: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "polling_interval",
    },
    clientId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "client_id",
    },
    scope: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "device_code",
} as const;
const environmentTable = {
  name: "environment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const environmentVariableTable = {
  name: "environmentVariable",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    environmentId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "environment_id",
    },
    resourceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    secretReferenceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "secret_reference_id",
    },
    encryptedValue: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "encrypted_value",
    },
    isBuildTime: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_build_time",
    },
    isSecret: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "is_secret",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "environment_variable",
} as const;
const gitProviderTable = {
  name: "gitProvider",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    appId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "app_id",
    },
    clientId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "client_id",
    },
    clientSecretReferenceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "client_secret_reference_id",
    },
    installationId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "installation_id",
    },
    webhookSecretReferenceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "webhook_secret_reference_id",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "git_provider",
} as const;
const gitRepositoryTable = {
  name: "gitRepository",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    gitProviderId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "git_provider_id",
    },
    owner: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    branch: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    rootDirectory: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "root_directory",
    },
    autoDeploy: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "auto_deploy",
    },
    webhookId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "webhook_id",
    },
    watchPaths: {
      type: "json",
      optional: true,
      customType: null as unknown as string[],
      serverName: "watch_paths",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "git_repository",
} as const;
const invitationTable = {
  name: "invitation",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    inviterId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "inviter_id",
    },
  },
  primaryKey: ["id"],
} as const;
const memberTable = {
  name: "member",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const notificationChannelTable = {
  name: "notificationChannel",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    type: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    config: {
      type: "json",
      optional: false,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "notificationChannel",
        "config"
      >,
    },
    enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    eventFilter: {
      type: "json",
      optional: true,
      customType: null as unknown as ReadonlyJSONValue,
      serverName: "event_filter",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "notification_channel",
} as const;
const organizationTable = {
  name: "organization",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    logo: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    metadata: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const projectTable = {
  name: "project",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    ownerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "owner_user_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    baseDomain: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "base_domain",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const resourceTable = {
  name: "resource",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    environmentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "environment_id",
    },
    serverId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "server_id",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "web"
        | "api"
        | "worker"
        | "database"
        | "compose",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "online"
        | "degraded"
        | "crashed"
        | "deploying"
        | "stopped"
        | "unknown",
    },
    deletedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "deleted_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const resourceBuildConfigTable = {
  name: "resourceBuildConfig",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    registryId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "registry_id",
    },
    builder: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "nixpacks"
        | "dockerfile"
        | "buildpack"
        | "railpack",
    },
    dockerfilePath: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "dockerfile_path",
    },
    buildCommand: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "build_command",
    },
    watchPatterns: {
      type: "json",
      optional: true,
      customType: null as unknown as string[],
      serverName: "watch_patterns",
    },
    rootDirectory: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "root_directory",
    },
    preDeployCommand: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "pre_deploy_command",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_build_config",
} as const;
const resourceComposeConfigTable = {
  name: "resourceComposeConfig",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    composeFile: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "compose_file",
    },
    composePath: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "compose_path",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_compose_config",
} as const;
const resourceJobConfigTable = {
  name: "resourceJobConfig",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    cronSchedule: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "cron_schedule",
    },
    cronCommand: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "cron_command",
    },
    overlapSeconds: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "overlap_seconds",
    },
    drainingSeconds: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "draining_seconds",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_job_config",
} as const;
const resourceMetricTable = {
  name: "resourceMetric",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    timestamp: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cpuPercent: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cpu_percent",
    },
    memoryUsed: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_used",
    },
    memoryLimit: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_limit",
    },
    networkRx: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "network_rx",
    },
    networkTx: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "network_tx",
    },
    diskRead: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "disk_read",
    },
    diskWrite: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "disk_write",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_metric",
} as const;
const resourceMetricHourlyTable = {
  name: "resourceMetricHourly",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    timestamp: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    cpuAvg: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cpu_avg",
    },
    cpuMax: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cpu_max",
    },
    cpuP95: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cpu_p95",
    },
    memoryAvg: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_avg",
    },
    memoryMax: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_max",
    },
    memoryP95: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_p95",
    },
    networkRxTotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "network_rx_total",
    },
    networkTxTotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "network_tx_total",
    },
    diskReadTotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "disk_read_total",
    },
    diskWriteTotal: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "disk_write_total",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_metric_hourly",
} as const;
const resourcePositionTable = {
  name: "resourcePosition",
  columns: {
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    posX: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "pos_x",
    },
    posY: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "pos_y",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["resourceId"],
  serverName: "resource_position",
} as const;
const resourceRuntimeConfigTable = {
  name: "resourceRuntimeConfig",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    port: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    startCommand: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "start_command",
    },
    restartPolicy: {
      type: "string",
      optional: true,
      customType: null as unknown as "ON_FAILURE" | "ALWAYS" | "NEVER",
      serverName: "restart_policy",
    },
    restartPolicyMaxRetries: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "restart_policy_max_retries",
    },
    replicas: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    cpuLimit: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "cpu_limit",
    },
    memoryLimit: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "memory_limit",
    },
    region: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sleepApplication: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "sleep_application",
    },
    healthCheckPath: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "health_check_path",
    },
    healthCheckInterval: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "health_check_interval",
    },
    healthCheckTimeout: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "health_check_timeout",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_runtime_config",
} as const;
const resourceVolumeTable = {
  name: "resourceVolume",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    driver: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    sizeGb: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "size_gb",
    },
    storageClass: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "storage_class",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_volume",
} as const;
const resourceVolumeMountTable = {
  name: "resourceVolumeMount",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    volumeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "volume_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    mountPath: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "mount_path",
    },
    readOnly: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "read_only",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "resource_volume_mount",
} as const;
const scheduledTaskExecutionTable = {
  name: "scheduledTaskExecution",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    resourceId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "resource_id",
    },
    command: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    cronExpression: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "cron_expression",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    exitCode: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "exit_code",
    },
    stdout: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    stderr: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    duration: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    startedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "started_at",
    },
    completedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "completed_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "scheduled_task_execution",
} as const;
const secretProviderBindingTable = {
  name: "secretProviderBinding",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    provider: {
      type: "string",
      optional: true,
      customType: null as unknown as "infisical" | "native_breakglass",
    },
    providerProjectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_project_id",
    },
    providerProjectSlug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_project_slug",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as "provisioning" | "error" | "active",
    },
    metadata: {
      type: "json",
      optional: true,
      customType: null as unknown as CustomType<
        typeof drizzleSchema,
        "secretProviderBinding",
        "metadata"
      >,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "secret_provider_binding",
} as const;
const secretReferenceTable = {
  name: "secretReference",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as "infisical" | "native_breakglass",
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "env_var"
        | "ssh_private_key"
        | "git_client_secret"
        | "git_webhook_secret",
    },
    logicalScope: {
      type: "string",
      optional: false,
      customType: null as unknown as
        | "organization"
        | "project"
        | "environment"
        | "resource",
      serverName: "logical_scope",
    },
    logicalScopeId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "logical_scope_id",
    },
    key: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    providerPath: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_path",
    },
    providerKey: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "provider_key",
    },
    providerVersion: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "provider_version",
    },
    lastResolvedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_resolved_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "secret_reference",
} as const;
const serverTable = {
  name: "server",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    ipAddress: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "ip_address",
    },
    port: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    sshKeyId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ssh_key_id",
    },
    status: {
      type: "string",
      optional: true,
      customType: null as unknown as
        | "connected"
        | "disconnected"
        | "provisioning"
        | "error",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as "worker" | "manager",
    },
    dockerVersion: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "docker_version",
    },
    os: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    arch: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    totalMemory: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_memory",
    },
    totalCpu: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_cpu",
    },
    totalDisk: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "total_disk",
    },
    swarmNodeId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "swarm_node_id",
    },
    baseDomain: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "base_domain",
    },
    dockerCleanupThreshold: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "docker_cleanup_threshold",
    },
    lastSeenAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "last_seen_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const sessionTable = {
  name: "session",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    token: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    ipAddress: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ip_address",
    },
    userAgent: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "user_agent",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    impersonatedBy: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "impersonated_by",
    },
    activeOrganizationId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "active_organization_id",
    },
  },
  primaryKey: ["id"],
} as const;
const sshKeyTable = {
  name: "sshKey",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    organizationId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "organization_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    publicKey: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "public_key",
    },
    privateKeySecretReferenceId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "private_key_secret_reference_id",
    },
    fingerprint: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "ssh_key",
} as const;
const twoFactorTable = {
  name: "twoFactor",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    secret: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    backupCodes: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "backup_codes",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
  },
  primaryKey: ["id"],
  serverName: "two_factor",
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    role: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    banned: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    banReason: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "ban_reason",
    },
    banExpires: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "ban_expires",
    },
    twoFactorEnabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "two_factor_enabled",
    },
  },
  primaryKey: ["id"],
} as const;
const verificationTable = {
  name: "verification",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    identifier: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    value: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    expiresAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "expires_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const viewportTable = {
  name: "viewport",
  columns: {
    environmentId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "environment_id",
    },
    x: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    y: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    zoom: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["environmentId"],
} as const;
const webhookDeliveryTable = {
  name: "webhookDelivery",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    receivedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "received_at",
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "webhook_delivery",
} as const;
const accountRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const apikeyRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const backupRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const backupScheduleRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const caddyInstanceRelationships = {
  server: [
    {
      sourceField: ["serverId"],
      destField: ["id"],
      destSchema: "server",
      cardinality: "one",
    },
  ],
} as const;
const configFileRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const containerRegistryRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const customDomainRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const databaseConfigRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const deploymentEventRelationships = {
  deployment: [
    {
      sourceField: ["deploymentId"],
      destField: ["id"],
      destSchema: "deployment",
      cardinality: "one",
    },
  ],
} as const;
const deploymentRelationships = {
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  environment: [
    {
      sourceField: ["environmentId"],
      destField: ["id"],
      destSchema: "environment",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  triggeredByUser: [
    {
      sourceField: ["triggeredBy"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  events: [
    {
      sourceField: ["id"],
      destField: ["deploymentId"],
      destSchema: "deploymentEvent",
      cardinality: "many",
    },
  ],
} as const;
const deploymentSecretSnapshotRelationships = {
  deployment: [
    {
      sourceField: ["deploymentId"],
      destField: ["id"],
      destSchema: "deployment",
      cardinality: "one",
    },
  ],
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const environmentRelationships = {
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  resources: [
    {
      sourceField: ["id"],
      destField: ["environmentId"],
      destSchema: "resource",
      cardinality: "many",
    },
  ],
  viewport: [
    {
      sourceField: ["id"],
      destField: ["environmentId"],
      destSchema: "viewport",
      cardinality: "one",
    },
  ],
} as const;
const environmentVariableRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  environment: [
    {
      sourceField: ["environmentId"],
      destField: ["id"],
      destSchema: "environment",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  secretReference: [
    {
      sourceField: ["secretReferenceId"],
      destField: ["id"],
      destSchema: "secretReference",
      cardinality: "one",
    },
  ],
} as const;
const gitProviderRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  repositories: [
    {
      sourceField: ["id"],
      destField: ["gitProviderId"],
      destSchema: "gitRepository",
      cardinality: "many",
    },
  ],
} as const;
const gitRepositoryRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
  provider: [
    {
      sourceField: ["gitProviderId"],
      destField: ["id"],
      destSchema: "gitProvider",
      cardinality: "one",
    },
  ],
} as const;
const invitationRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["inviterId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const memberRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const notificationChannelRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const organizationRelationships = {
  members: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["organizationId"],
      destSchema: "invitation",
      cardinality: "many",
    },
  ],
} as const;
const projectRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  owner: [
    {
      sourceField: ["ownerId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
  environments: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "environment",
      cardinality: "many",
    },
  ],
} as const;
const resourceBuildConfigRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceComposeConfigRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceJobConfigRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceMetricRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourcePositionRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  project: [
    {
      sourceField: ["projectId"],
      destField: ["id"],
      destSchema: "project",
      cardinality: "one",
    },
  ],
  environment: [
    {
      sourceField: ["environmentId"],
      destField: ["id"],
      destSchema: "environment",
      cardinality: "one",
    },
  ],
  position: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourcePosition",
      cardinality: "one",
    },
  ],
  runtimeConfig: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourceRuntimeConfig",
      cardinality: "one",
    },
  ],
  buildConfig: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourceBuildConfig",
      cardinality: "one",
    },
  ],
  jobConfig: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourceJobConfig",
      cardinality: "one",
    },
  ],
  composeConfig: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourceComposeConfig",
      cardinality: "one",
    },
  ],
  databaseConfig: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "databaseConfig",
      cardinality: "one",
    },
  ],
  volumeMounts: [
    {
      sourceField: ["id"],
      destField: ["resourceId"],
      destSchema: "resourceVolumeMount",
      cardinality: "many",
    },
  ],
} as const;
const resourceRuntimeConfigRelationships = {
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceVolumeMountRelationships = {
  volume: [
    {
      sourceField: ["volumeId"],
      destField: ["id"],
      destSchema: "resourceVolume",
      cardinality: "one",
    },
  ],
  resource: [
    {
      sourceField: ["resourceId"],
      destField: ["id"],
      destSchema: "resource",
      cardinality: "one",
    },
  ],
} as const;
const resourceVolumeRelationships = {
  mounts: [
    {
      sourceField: ["id"],
      destField: ["volumeId"],
      destSchema: "resourceVolumeMount",
      cardinality: "many",
    },
  ],
} as const;
const secretProviderBindingRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const secretReferenceRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const serverRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
  sshKey: [
    {
      sourceField: ["sshKeyId"],
      destField: ["id"],
      destSchema: "sshKey",
      cardinality: "one",
    },
  ],
} as const;
const sessionRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const sshKeyRelationships = {
  organization: [
    {
      sourceField: ["organizationId"],
      destField: ["id"],
      destSchema: "organization",
      cardinality: "one",
    },
  ],
} as const;
const twoFactorRelationships = {
  user: [
    {
      sourceField: ["userId"],
      destField: ["id"],
      destSchema: "user",
      cardinality: "one",
    },
  ],
} as const;
const userRelationships = {
  sessions: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "session",
      cardinality: "many",
    },
  ],
  accounts: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "account",
      cardinality: "many",
    },
  ],
  members: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "member",
      cardinality: "many",
    },
  ],
  invitations: [
    {
      sourceField: ["id"],
      destField: ["inviterId"],
      destSchema: "invitation",
      cardinality: "many",
    },
  ],
  apikeys: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "apikey",
      cardinality: "many",
    },
  ],
  twoFactors: [
    {
      sourceField: ["id"],
      destField: ["userId"],
      destSchema: "twoFactor",
      cardinality: "many",
    },
  ],
} as const;
const viewportRelationships = {
  environment: [
    {
      sourceField: ["environmentId"],
      destField: ["id"],
      destSchema: "environment",
      cardinality: "one",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    account: accountTable,
    apikey: apikeyTable,
    auditLog: auditLogTable,
    backup: backupTable,
    backupSchedule: backupScheduleTable,
    caddyInstance: caddyInstanceTable,
    configFile: configFileTable,
    containerRegistry: containerRegistryTable,
    customDomain: customDomainTable,
    databaseConfig: databaseConfigTable,
    deployment: deploymentTable,
    deploymentEvent: deploymentEventTable,
    deploymentSecretSnapshot: deploymentSecretSnapshotTable,
    deviceCode: deviceCodeTable,
    environment: environmentTable,
    environmentVariable: environmentVariableTable,
    gitProvider: gitProviderTable,
    gitRepository: gitRepositoryTable,
    invitation: invitationTable,
    member: memberTable,
    notificationChannel: notificationChannelTable,
    organization: organizationTable,
    project: projectTable,
    resource: resourceTable,
    resourceBuildConfig: resourceBuildConfigTable,
    resourceComposeConfig: resourceComposeConfigTable,
    resourceJobConfig: resourceJobConfigTable,
    resourceMetric: resourceMetricTable,
    resourceMetricHourly: resourceMetricHourlyTable,
    resourcePosition: resourcePositionTable,
    resourceRuntimeConfig: resourceRuntimeConfigTable,
    resourceVolume: resourceVolumeTable,
    resourceVolumeMount: resourceVolumeMountTable,
    scheduledTaskExecution: scheduledTaskExecutionTable,
    secretProviderBinding: secretProviderBindingTable,
    secretReference: secretReferenceTable,
    server: serverTable,
    session: sessionTable,
    sshKey: sshKeyTable,
    twoFactor: twoFactorTable,
    user: userTable,
    verification: verificationTable,
    viewport: viewportTable,
    webhookDelivery: webhookDeliveryTable,
  },
  relationships: {
    account: accountRelationships,
    apikey: apikeyRelationships,
    backup: backupRelationships,
    backupSchedule: backupScheduleRelationships,
    caddyInstance: caddyInstanceRelationships,
    configFile: configFileRelationships,
    containerRegistry: containerRegistryRelationships,
    customDomain: customDomainRelationships,
    databaseConfig: databaseConfigRelationships,
    deploymentEvent: deploymentEventRelationships,
    deployment: deploymentRelationships,
    deploymentSecretSnapshot: deploymentSecretSnapshotRelationships,
    environment: environmentRelationships,
    environmentVariable: environmentVariableRelationships,
    gitProvider: gitProviderRelationships,
    gitRepository: gitRepositoryRelationships,
    invitation: invitationRelationships,
    member: memberRelationships,
    notificationChannel: notificationChannelRelationships,
    organization: organizationRelationships,
    project: projectRelationships,
    resourceBuildConfig: resourceBuildConfigRelationships,
    resourceComposeConfig: resourceComposeConfigRelationships,
    resourceJobConfig: resourceJobConfigRelationships,
    resourceMetric: resourceMetricRelationships,
    resourcePosition: resourcePositionRelationships,
    resource: resourceRelationships,
    resourceRuntimeConfig: resourceRuntimeConfigRelationships,
    resourceVolumeMount: resourceVolumeMountRelationships,
    resourceVolume: resourceVolumeRelationships,
    secretProviderBinding: secretProviderBindingRelationships,
    secretReference: secretReferenceRelationships,
    server: serverRelationships,
    session: sessionRelationships,
    sshKey: sshKeyRelationships,
    twoFactor: twoFactorRelationships,
    user: userRelationships,
    viewport: viewportRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<(typeof schema)["tables"]["account"]>;
/**
 * Represents a row from the "apikey" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Apikey = Row<(typeof schema)["tables"]["apikey"]>;
/**
 * Represents a row from the "auditLog" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AuditLog = Row<(typeof schema)["tables"]["auditLog"]>;
/**
 * Represents a row from the "backup" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Backup = Row<(typeof schema)["tables"]["backup"]>;
/**
 * Represents a row from the "backupSchedule" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type BackupSchedule = Row<(typeof schema)["tables"]["backupSchedule"]>;
/**
 * Represents a row from the "caddyInstance" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CaddyInstance = Row<(typeof schema)["tables"]["caddyInstance"]>;
/**
 * Represents a row from the "configFile" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ConfigFile = Row<(typeof schema)["tables"]["configFile"]>;
/**
 * Represents a row from the "containerRegistry" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ContainerRegistry = Row<
  (typeof schema)["tables"]["containerRegistry"]
>;
/**
 * Represents a row from the "customDomain" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type CustomDomain = Row<(typeof schema)["tables"]["customDomain"]>;
/**
 * Represents a row from the "databaseConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DatabaseConfig = Row<(typeof schema)["tables"]["databaseConfig"]>;
/**
 * Represents a row from the "deployment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Deployment = Row<(typeof schema)["tables"]["deployment"]>;
/**
 * Represents a row from the "deploymentEvent" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DeploymentEvent = Row<(typeof schema)["tables"]["deploymentEvent"]>;
/**
 * Represents a row from the "deploymentSecretSnapshot" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DeploymentSecretSnapshot = Row<
  (typeof schema)["tables"]["deploymentSecretSnapshot"]
>;
/**
 * Represents a row from the "deviceCode" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type DeviceCode = Row<(typeof schema)["tables"]["deviceCode"]>;
/**
 * Represents a row from the "environment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Environment = Row<(typeof schema)["tables"]["environment"]>;
/**
 * Represents a row from the "environmentVariable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type EnvironmentVariable = Row<
  (typeof schema)["tables"]["environmentVariable"]
>;
/**
 * Represents a row from the "gitProvider" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GitProvider = Row<(typeof schema)["tables"]["gitProvider"]>;
/**
 * Represents a row from the "gitRepository" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GitRepository = Row<(typeof schema)["tables"]["gitRepository"]>;
/**
 * Represents a row from the "invitation" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invitation = Row<(typeof schema)["tables"]["invitation"]>;
/**
 * Represents a row from the "member" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Member = Row<(typeof schema)["tables"]["member"]>;
/**
 * Represents a row from the "notificationChannel" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type NotificationChannel = Row<
  (typeof schema)["tables"]["notificationChannel"]
>;
/**
 * Represents a row from the "organization" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Organization = Row<(typeof schema)["tables"]["organization"]>;
/**
 * Represents a row from the "project" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)["tables"]["project"]>;
/**
 * Represents a row from the "resource" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Resource = Row<(typeof schema)["tables"]["resource"]>;
/**
 * Represents a row from the "resourceBuildConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceBuildConfig = Row<
  (typeof schema)["tables"]["resourceBuildConfig"]
>;
/**
 * Represents a row from the "resourceComposeConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceComposeConfig = Row<
  (typeof schema)["tables"]["resourceComposeConfig"]
>;
/**
 * Represents a row from the "resourceJobConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceJobConfig = Row<
  (typeof schema)["tables"]["resourceJobConfig"]
>;
/**
 * Represents a row from the "resourceMetric" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceMetric = Row<(typeof schema)["tables"]["resourceMetric"]>;
/**
 * Represents a row from the "resourceMetricHourly" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceMetricHourly = Row<
  (typeof schema)["tables"]["resourceMetricHourly"]
>;
/**
 * Represents a row from the "resourcePosition" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourcePosition = Row<
  (typeof schema)["tables"]["resourcePosition"]
>;
/**
 * Represents a row from the "resourceRuntimeConfig" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceRuntimeConfig = Row<
  (typeof schema)["tables"]["resourceRuntimeConfig"]
>;
/**
 * Represents a row from the "resourceVolume" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceVolume = Row<(typeof schema)["tables"]["resourceVolume"]>;
/**
 * Represents a row from the "resourceVolumeMount" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ResourceVolumeMount = Row<
  (typeof schema)["tables"]["resourceVolumeMount"]
>;
/**
 * Represents a row from the "scheduledTaskExecution" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ScheduledTaskExecution = Row<
  (typeof schema)["tables"]["scheduledTaskExecution"]
>;
/**
 * Represents a row from the "secretProviderBinding" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SecretProviderBinding = Row<
  (typeof schema)["tables"]["secretProviderBinding"]
>;
/**
 * Represents a row from the "secretReference" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SecretReference = Row<(typeof schema)["tables"]["secretReference"]>;
/**
 * Represents a row from the "server" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Server = Row<(typeof schema)["tables"]["server"]>;
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)["tables"]["session"]>;
/**
 * Represents a row from the "sshKey" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type SshKey = Row<(typeof schema)["tables"]["sshKey"]>;
/**
 * Represents a row from the "twoFactor" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TwoFactor = Row<(typeof schema)["tables"]["twoFactor"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Verification = Row<(typeof schema)["tables"]["verification"]>;
/**
 * Represents a row from the "viewport" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Viewport = Row<(typeof schema)["tables"]["viewport"]>;
/**
 * Represents a row from the "webhookDelivery" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type WebhookDelivery = Row<(typeof schema)["tables"]["webhookDelivery"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
