import {
  Rocket,
  GitBranch,
  Activity,
  Database,
  Server,
  Lock,
  Puzzle,
} from "lucide-react";

export const SATELLITE_NODES = [
  { label: ".WEB", x: -100, y: -40 },
  { label: ".API", x: 230, y: -50 },
  { label: ".DB", x: 250, y: 80 },
  { label: ".CACHE", x: -110, y: 90 },
  { label: ".WORKER", x: 70, y: 200 },
];

export const GRID_CELLS = [
  { label: "web", r: 0, c: 0 },
  { label: "api", r: 0, c: 1 },
  { label: "worker", r: 0, c: 2 },
  { label: "db", r: 1, c: 0 },
  { label: "secrets", r: 1, c: 1 },
  { label: "logs", r: 1, c: 2 },
  { label: "config", r: 2, c: 0 },
];

export const DEPLOY_LINES = [
  { text: "$ curl -fsSL https://get.otterdeploy.sh | sh", type: "command" as const },
  { text: "", type: "blank" as const },
  { text: "otterdeploy v2.4.0 \u2014 installing...", type: "brand" as const },
  { text: "", type: "blank" as const },
  { text: "\u2192 Downloading binary...", type: "header" as const },
  { text: "  \u2713 otterdeploy-linux-amd64   4.2MB", type: "success" as const },
  { text: "  \u2713 Binary installed to /usr/local/bin", type: "success" as const },
  { text: "", type: "blank" as const },
  { text: "\u2192 Bootstrapping platform...", type: "header" as const },
  { text: "  \u2713 Docker daemon    Connected", type: "success" as const },
  { text: "  \u2713 PostgreSQL       Running", type: "success" as const },
  { text: "  \u2713 Redis            Running", type: "success" as const },
  { text: "  \u2713 Caddy          \u2192 https://deploy.myserver.com", type: "success" as const },
  { text: "  \u2713 SSL certificates \u2192 Let's Encrypt (auto)", type: "success" as const },
  { text: "", type: "blank" as const },
  { text: "\u2713 Platform ready! Dashboard at https://deploy.myserver.com", type: "final" as const },
];

export const FEATURE_TABS = [
  {
    key: "deploy",
    label: "deploy",
    icon: <Rocket size={16} />,
    heading: "Flexible Application Deployment",
    desc: "Deploy any application using Nixpacks, Heroku Buildpacks, or your custom Dockerfile, tailored to your stack.",
    bullets: [
      "Nixpacks auto-detection for Node, Python, Go, Rust, PHP, Ruby, Java, .NET",
      "Full Dockerfile support for custom build pipelines",
      "Docker Compose native for multi-service orchestration",
      "Heroku Buildpacks compatibility for easy migration",
    ],
    terminal: {
      title: "deploy.sh",
      lines: [
        { text: "$ otter deploy ./myapp", type: "command" },
        { text: "", type: "blank" },
        { text: "\u2192 Detecting runtime...", type: "header" },
        { text: "  \u2713 Detected: Node.js 20 (via Nixpacks)", type: "success" },
        { text: "  \u2713 Dependencies installed (8s)", type: "success" },
        { text: "  \u2713 Build complete (12s)", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2192 Deploying to production...", type: "header" },
        { text: "  \u2713 Container started", type: "success" },
        { text: "  \u2713 Health check passed", type: "success" },
        { text: "  \u2713 Traffic routed \u2192 myapp.com", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2713 Deploy complete! (22s)", type: "final" },
      ],
    },
  },
  {
    key: "git",
    label: "git push",
    icon: <GitBranch size={16} />,
    heading: "Push to Deploy",
    desc: "Connect your Git repository and every push triggers an automatic build and zero-downtime deployment. Preview environments for every pull request.",
    bullets: [
      "GitHub, GitLab, Bitbucket, and Gitea integration",
      "Automatic builds triggered on every push",
      "PR preview environments with unique URLs",
      "Instant rollbacks to any previous deployment",
    ],
    terminal: {
      title: "git-deploy.sh",
      lines: [
        { text: "$ git push origin main", type: "command" },
        { text: "", type: "blank" },
        { text: "\u25b8 Webhook received from GitHub", type: "metric" },
        { text: "\u25b8 Build #1248 triggered", type: "metric" },
        { text: "", type: "blank" },
        { text: "\u2192 Building...", type: "header" },
        { text: "  \u2713 web        Built in 8s", type: "success" },
        { text: "  \u2713 api        Built in 5s", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2192 Rolling deploy (zero downtime)...", type: "header" },
        { text: "  \u2713 web        \u2192 myapp.com", type: "success" },
        { text: "  \u2713 api        \u2192 api.myapp.com", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2713 Production live! Build #1248 (18s)", type: "final" },
      ],
    },
  },
  {
    key: "monitor",
    label: "monitor",
    icon: <Activity size={16} />,
    heading: "Real-time Monitoring & Logs",
    desc: "Monitor your entire stack from a single pane. Live log streaming, health checks, resource metrics, and alerting across all your services.",
    bullets: [
      "Live log streaming across all services",
      "CPU, memory, disk, and network metrics in real-time",
      "Health check dashboards with uptime tracking",
      "Notifications via Slack, Discord, Telegram, and email",
    ],
    terminal: {
      title: "monitor.sh",
      lines: [
        { text: "$ otter logs --tail --service api", type: "command" },
        { text: "", type: "blank" },
        { text: "[12:04:01] 200 GET  /health       2ms", type: "log" },
        { text: "[12:04:03] 200 POST /api/users   18ms", type: "log" },
        { text: "[12:04:05] 200 GET  /api/items    4ms", type: "log" },
        { text: "[12:04:06] 201 POST /api/deploy  42ms", type: "log" },
        { text: "[12:04:08] 200 GET  /api/status   1ms", type: "log" },
        { text: "", type: "blank" },
        { text: "\u25b8 cpu: 23%  mem: 412MB  req/s: 1.2k", type: "metric" },
        { text: "\u25b8 uptime: 99.99%  p99: 48ms", type: "metric" },
      ],
    },
  },
  {
    key: "backup",
    label: "backup",
    icon: <Database size={16} />,
    heading: "Database Management & Backups",
    desc: "Manage and back up all your databases directly. Scheduled backups to S3-compatible storage with one-click restore.",
    bullets: [
      "PostgreSQL, MySQL, MongoDB, MariaDB, and Redis support",
      "Scheduled automatic backups to any S3-compatible storage",
      "One-click database restore from any backup point",
      "Connection pooling and resource management built in",
    ],
    terminal: {
      title: "backup.sh",
      lines: [
        { text: "$ otter db backup --all", type: "command" },
        { text: "", type: "blank" },
        { text: "\u2192 Creating backups...", type: "header" },
        { text: "  \u2713 postgres    42MB  \u2192 s3://backups/pg-2026-02-22.sql.gz", type: "success" },
        { text: "  \u2713 redis       8MB   \u2192 s3://backups/redis-2026-02-22.rdb", type: "success" },
        { text: "  \u2713 mongodb     126MB \u2192 s3://backups/mongo-2026-02-22.gz", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2713 All databases backed up successfully", type: "final" },
        { text: "\u25b8 Next scheduled: 2026-02-23 03:00 UTC", type: "metric" },
      ],
    },
  },
  {
    key: "scale",
    label: "scale",
    icon: <Server size={16} />,
    heading: "Multi-Server & Scaling",
    desc: "Deploy across multiple servers with Docker Swarm. Scale horizontally with a single command as your traffic grows.",
    bullets: [
      "Docker Swarm clustering for multi-node deployments",
      "Horizontal auto-scaling based on CPU/memory thresholds",
      "Load balancer configuration with Caddy",
      "Resource limits and quotas per service",
    ],
    terminal: {
      title: "scale.sh",
      lines: [
        { text: "$ otter scale web --replicas 4", type: "command" },
        { text: "", type: "blank" },
        { text: "\u2192 Scaling web: 2 \u2192 4 replicas", type: "header" },
        { text: "  \u2713 replica-1   Running  (node-1)", type: "success" },
        { text: "  \u2713 replica-2   Running  (node-1)", type: "success" },
        { text: "  \u2713 replica-3   Running  (node-2)", type: "success" },
        { text: "  \u2713 replica-4   Running  (node-2)", type: "success" },
        { text: "  \u2713 Load balancer updated", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2713 web scaled to 4 replicas across 2 nodes", type: "final" },
        { text: "\u25b8 avg cpu: 34% \u2192 18%  avg mem: 380MB \u2192 210MB", type: "metric" },
      ],
    },
  },
  {
    key: "ssl",
    label: "ssl",
    icon: <Lock size={16} />,
    heading: "SSL, Domains & Caddy",
    desc: "Automatic TLS certificates via Let's Encrypt for every service. Domain management and reverse proxy powered by Caddy.",
    bullets: [
      "Automatic Let's Encrypt SSL with auto-renewal",
      "Custom domain mapping per service",
      "Caddy reverse proxy with automatic routing",
      "Wildcard certificates and multi-domain support",
    ],
    terminal: {
      title: "domains.sh",
      lines: [
        { text: "$ otter domains add myapp.com --service web", type: "command" },
        { text: "", type: "blank" },
        { text: "\u2192 Configuring domain...", type: "header" },
        { text: "  \u2713 DNS verified for myapp.com", type: "success" },
        { text: "  \u2713 SSL certificate issued (Let's Encrypt)", type: "success" },
        { text: "  \u2713 Caddy route configured", type: "success" },
        { text: "  \u2713 HTTPS redirect enabled", type: "success" },
        { text: "", type: "blank" },
        { text: "\u2713 myapp.com \u2192 web:3000 (TLS active)", type: "final" },
        { text: "\u25b8 Cert expires: 2026-05-22 (auto-renew)", type: "metric" },
      ],
    },
  },
  {
    key: "templates",
    label: "templates",
    icon: <Puzzle size={16} />,
    heading: "One-Click Service Templates",
    desc: "Get started quickly with 120+ pre-configured templates for popular tools. Deploy production-ready services in seconds.",
    bullets: [
      "Supabase, PocketBase, Appwrite, and more",
      "Cal.com, Plausible, Umami analytics",
      "Ghost, WordPress, Strapi CMS",
      "MinIO, Grafana, Prometheus, and 100+ more",
    ],
    terminal: {
      title: "templates.sh",
      lines: [
        { text: "$ otter template list", type: "command" },
        { text: "", type: "blank" },
        { text: "  supabase       Backend-as-a-Service      \u2605 4.2k", type: "log" },
        { text: "  pocketbase     Lightweight BaaS           \u2605 3.1k", type: "log" },
        { text: "  plausible      Privacy-first analytics    \u2605 2.8k", type: "log" },
        { text: "  ghost          Publishing platform        \u2605 2.4k", type: "log" },
        { text: "  grafana        Observability platform     \u2605 1.9k", type: "log" },
        { text: "", type: "blank" },
        { text: "  ... and 115 more templates", type: "metric" },
        { text: "", type: "blank" },
        { text: "$ otter template deploy supabase", type: "command" },
        { text: "\u2713 Supabase deployed at supabase.myserver.com", type: "final" },
      ],
    },
  },
];

export const CONTRIBUTOR_AVATARS = [
  { initials: "SK", color: "#7c3aed" },
  { initials: "MJ", color: "#2563eb" },
  { initials: "JD", color: "#059669" },
  { initials: "AR", color: "#d97706" },
  { initials: "LP", color: "#dc2626" },
  { initials: "NW", color: "#7c3aed" },
  { initials: "TH", color: "#2563eb" },
  { initials: "RG", color: "#059669" },
  { initials: "CM", color: "#d97706" },
  { initials: "YB", color: "#dc2626" },
  { initials: "EF", color: "#7c3aed" },
  { initials: "OQ", color: "#2563eb" },
  { initials: "DK", color: "#059669" },
  { initials: "PL", color: "#d97706" },
  { initials: "WS", color: "#dc2626" },
  { initials: "HM", color: "#7c3aed" },
  { initials: "ZA", color: "#2563eb" },
  { initials: "BT", color: "#059669" },
];

export const TESTIMONIALS = [
  {
    quote:
      "We migrated from Heroku to Otterdeploy in 15 minutes. Cut our hosting bill by 80% and now we own our entire stack. The one-command install is genuinely that simple.",
    author: "Priya M.",
    role: "DevOps Engineer, Startly",
  },
  {
    quote:
      "Finally, self-hosted infrastructure I can actually version control. The declarative YAML config and push-to-deploy workflow means our team ships faster without the PaaS tax.",
    author: "Alex R.",
    role: "CTO, Shipfast",
  },
  {
    quote:
      "The plugin system is brilliant. Built a custom deploy hook in an afternoon, upstream'd it the next day. 42 contributors and growing \u2014 that's the power of open source.",
    author: "Tom H.",
    role: "Platform Engineer",
  },
];
