/**
 * The tracker snippet, rendered as code rather than as a mono string.
 *
 * It was going through JoinCommandBlock, which is a plain uncoloured block
 * built for a shell one-liner. This is HTML, and the app already has a house
 * way to draw code: caddyfile-highlight.ts tokenizes and maps each kind to a
 * class carrying BOTH theme shades, because the pale `-300` steps that read on
 * the dark canvas are near-invisible on the light one. Same vocabulary here,
 * on the four kinds an HTML tag actually has.
 *
 * Colour does real work in this particular block. The one thing an operator
 * has to check is that `data-key` matches their project, and an undifferentiated
 * 100-character string is exactly where a wrong key hides. Painting the value
 * apart from the attribute name and the tag makes it findable at a glance.
 *
 * The tokenizer is deliberately tolerant: this string is generated by our own
 * server (`analytics.setup`), but anything it fails to recognise falls through
 * to `plain` rather than being dropped, so a future change to the snippet's
 * shape can degrade to uncoloured text and never to missing text.
 */

import { useState } from "react";

import { Copy01Icon, Tick02Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";

import { Button } from "@/shared/components/ui/button";
import { copyToClipboard } from "@/shared/lib/clipboard";
import { cn } from "@/shared/lib/utils";

type SnippetToken = "tag" | "attr" | "string" | "punct" | "plain";

/** Mirrors KIND_CLASS in caddyfile-highlight.ts — same shades, so the two code
 *  surfaces read as one system rather than two palettes. */
const TOKEN_CLASS: Record<SnippetToken, string> = {
  tag: "text-sky-700 dark:text-sky-300/90",
  attr: "text-amber-700 dark:text-orange-300/85",
  string: "text-emerald-700 dark:text-emerald-300/85",
  punct: "text-muted-foreground/70",
  plain: "text-foreground/85",
};

/**
 * Split an HTML tag into coloured runs. Not a parser — a scanner over the four
 * shapes this snippet contains: `<tag`, `attr=`, `"value"`, and the angle
 * brackets between them.
 */
function tokenizeSnippet(source: string): { text: string; kind: SnippetToken }[] {
  const out: { text: string; kind: SnippetToken }[] = [];
  let index = 0;
  while (index < source.length) {
    const rest = source.slice(index);
    let match: RegExpExecArray | null;
    if ((match = /^<\/?[a-zA-Z][\w-]*/.exec(rest))) out.push({ text: match[0], kind: "tag" });
    else if ((match = /^("[^"]*"|'[^']*')/.exec(rest)))
      out.push({ text: match[0], kind: "string" });
    else if ((match = /^[a-zA-Z_:][\w:.-]*(?==)/.exec(rest)))
      out.push({ text: match[0], kind: "attr" });
    else if ((match = /^[<>/=]+/.exec(rest))) out.push({ text: match[0], kind: "punct" });
    else if ((match = /^[^<>/="']+/.exec(rest))) out.push({ text: match[0], kind: "plain" });
    else {
      // Nothing matched: emit one character as plain so the loop always
      // advances. A tokenizer that can stall is worse than one that miscolours.
      out.push({ text: rest[0] ?? "", kind: "plain" });
      index += 1;
      continue;
    }
    index += match[0].length;
  }
  return out;
}

export function SnippetBlock({ snippet }: { snippet: string }) {
  const [copied, setCopied] = useState(false);

  const copy = () => {
    void copyToClipboard(snippet).then((ok) => {
      if (!ok) return;
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  const tokens = tokenizeSnippet(snippet);

  return (
    <div className="relative rounded-md border bg-muted/50 p-3 pr-11 font-mono text-[12px] leading-relaxed">
      {/* `break-words`, not `break-all`: break-all splits at whatever character
          reaches the edge, which cut a key into `od_7e5dae55b3449e` /
          `dcfc824029e708c2ff` across two lines — unverifiable by eye against
          the value it is meant to match. This breaks at spaces first and only
          splits a token wider than the line. */}
      <code className="block break-words whitespace-pre-wrap">
        {tokens.map((token, i) => (
          // Index keys: the list is a positional decomposition of one string,
          // re-derived whenever that string changes, so there is no identity to
          // preserve across renders.
          <span key={i} className={TOKEN_CLASS[token.kind]}>
            {token.text}
          </span>
        ))}
      </code>
      <Button
        type="button"
        variant="outline"
        size="icon-sm"
        onClick={copy}
        aria-label={copied ? "Copied" : "Copy snippet"}
        className={cn("absolute top-2 right-2 size-7 bg-background", copied && "text-success")}
      >
        <HugeiconsIcon
          icon={copied ? Tick02Icon : Copy01Icon}
          strokeWidth={2}
          className="size-3.5"
        />
      </Button>
    </div>
  );
}
