/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardProjectLayoutRouteImport } from './routes/_dashboard/project/layout'
import { Route as DashboardProjectProjectIdLayoutRouteImport } from './routes/_dashboard/project/$projectId/layout'
import { Route as DashboardProjectProjectIdIndexRouteImport } from './routes/_dashboard/project/$projectId/index'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardProjectLayoutRoute = DashboardProjectLayoutRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProjectProjectIdLayoutRoute =
  DashboardProjectProjectIdLayoutRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectLayoutRoute,
  } as any)
const DashboardProjectProjectIdIndexRoute =
  DashboardProjectProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectProjectIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/project': typeof DashboardProjectLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/project/$projectId': typeof DashboardProjectProjectIdLayoutRouteWithChildren
  '/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/project': typeof DashboardProjectLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof DashboardIndexRoute
  '/project/$projectId': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/_dashboard/project': typeof DashboardProjectLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/project/$projectId': typeof DashboardProjectProjectIdLayoutRouteWithChildren
  '/_dashboard/project/$projectId/': typeof DashboardProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/project'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/project/$projectId'
    | '/project/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/project'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/_dashboard/project'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_dashboard/'
    | '/_dashboard/project/$projectId'
    | '/_dashboard/project/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/project': {
      id: '/_dashboard/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof DashboardProjectLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/project/$projectId': {
      id: '/_dashboard/project/$projectId'
      path: '/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof DashboardProjectProjectIdLayoutRouteImport
      parentRoute: typeof DashboardProjectLayoutRoute
    }
    '/_dashboard/project/$projectId/': {
      id: '/_dashboard/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof DashboardProjectProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectProjectIdLayoutRoute
    }
  }
}

interface DashboardProjectProjectIdLayoutRouteChildren {
  DashboardProjectProjectIdIndexRoute: typeof DashboardProjectProjectIdIndexRoute
}

const DashboardProjectProjectIdLayoutRouteChildren: DashboardProjectProjectIdLayoutRouteChildren =
  {
    DashboardProjectProjectIdIndexRoute: DashboardProjectProjectIdIndexRoute,
  }

const DashboardProjectProjectIdLayoutRouteWithChildren =
  DashboardProjectProjectIdLayoutRoute._addFileChildren(
    DashboardProjectProjectIdLayoutRouteChildren,
  )

interface DashboardProjectLayoutRouteChildren {
  DashboardProjectProjectIdLayoutRoute: typeof DashboardProjectProjectIdLayoutRouteWithChildren
}

const DashboardProjectLayoutRouteChildren: DashboardProjectLayoutRouteChildren =
  {
    DashboardProjectProjectIdLayoutRoute:
      DashboardProjectProjectIdLayoutRouteWithChildren,
  }

const DashboardProjectLayoutRouteWithChildren =
  DashboardProjectLayoutRoute._addFileChildren(
    DashboardProjectLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardProjectLayoutRoute: typeof DashboardProjectLayoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardProjectLayoutRoute: DashboardProjectLayoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
