/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TerminalRouteImport } from "./routes/terminal"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as DeviceRouteImport } from "./routes/device"
import { Route as AppLayoutRouteImport } from "./routes/_app/layout"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as OnboardingCreateOrganizationRouteImport } from "./routes/onboarding/create-organization"
import { Route as AcceptInviteInvitationIdRouteImport } from "./routes/accept-invite.$invitationId"
import { Route as AppOrgSlugLayoutRouteImport } from "./routes/_app/$orgSlug/layout"
import { Route as AppOrgSlugIndexRouteImport } from "./routes/_app/$orgSlug/index"
import { Route as AppOrgSlugTerminalRouteImport } from "./routes/_app/$orgSlug/terminal"
import { Route as AppOrgSlugTeamRouteImport } from "./routes/_app/$orgSlug/team"
import { Route as AppOrgSlugSshKeysRouteImport } from "./routes/_app/$orgSlug/ssh-keys"
import { Route as AppOrgSlugSettingsRouteImport } from "./routes/_app/$orgSlug/settings"
import { Route as AppOrgSlugServersRouteImport } from "./routes/_app/$orgSlug/servers"
import { Route as AppOrgSlugRegistriesRouteImport } from "./routes/_app/$orgSlug/registries"
import { Route as AppOrgSlugPlatformRouteImport } from "./routes/_app/$orgSlug/platform"
import { Route as AppOrgSlugNotificationsRouteImport } from "./routes/_app/$orgSlug/notifications"
import { Route as AppOrgSlugNetworkingRouteImport } from "./routes/_app/$orgSlug/networking"
import { Route as AppOrgSlugInstanceRouteImport } from "./routes/_app/$orgSlug/instance"
import { Route as AppOrgSlugGitProvidersRouteImport } from "./routes/_app/$orgSlug/git-providers"
import { Route as AppOrgSlugFirewallRouteImport } from "./routes/_app/$orgSlug/firewall"
import { Route as AppOrgSlugEdgeLogsRouteImport } from "./routes/_app/$orgSlug/edge-logs"
import { Route as AppOrgSlugDockerRouteImport } from "./routes/_app/$orgSlug/docker"
import { Route as AppOrgSlugBackupsRouteImport } from "./routes/_app/$orgSlug/backups"
import { Route as AppOrgSlugAuditRouteImport } from "./routes/_app/$orgSlug/audit"
import { Route as AppOrgSlugApiKeysRouteImport } from "./routes/_app/$orgSlug/api-keys"
import { Route as AppOrgSlugProjectSlugLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/layout"
import { Route as AppOrgSlugProjectSlugIndexRouteImport } from "./routes/_app/$orgSlug/$projectSlug/index"
import { Route as AppOrgSlugGithubAppProviderIdRouteImport } from "./routes/_app/$orgSlug/github-app.$providerId"
import { Route as AppOrgSlugGitProvidersProviderIdRouteImport } from "./routes/_app/$orgSlug/git-providers.$providerId"
import { Route as AppOrgSlugProjectSlugVariablesRouteImport } from "./routes/_app/$orgSlug/$projectSlug/variables"
import { Route as AppOrgSlugProjectSlugSettingsRouteImport } from "./routes/_app/$orgSlug/$projectSlug/settings"
import { Route as AppOrgSlugProjectSlugNetworkingRouteImport } from "./routes/_app/$orgSlug/$projectSlug/networking"
import { Route as AppOrgSlugProjectSlugMetricsRouteImport } from "./routes/_app/$orgSlug/$projectSlug/metrics"
import { Route as AppOrgSlugProjectSlugLogsRouteImport } from "./routes/_app/$orgSlug/$projectSlug/logs"
import { Route as AppOrgSlugProjectSlugEdgeLogsRouteImport } from "./routes/_app/$orgSlug/$projectSlug/edge-logs"
import { Route as AppOrgSlugProjectSlugGraphLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/layout"
import { Route as AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/$resourceId/layout"
import { Route as AppOrgSlugProjectSlugGraphPreviewPreviewIdRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/preview.$previewId"
import { Route as AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"

const TerminalRoute = TerminalRouteImport.update({
  id: "/terminal",
  path: "/terminal",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: "/device",
  path: "/device",
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppLayoutRoute,
} as any)
const OnboardingCreateOrganizationRoute =
  OnboardingCreateOrganizationRouteImport.update({
    id: "/onboarding/create-organization",
    path: "/onboarding/create-organization",
    getParentRoute: () => rootRouteImport,
  } as any)
const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: "/accept-invite/$invitationId",
    path: "/accept-invite/$invitationId",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrgSlugLayoutRoute = AppOrgSlugLayoutRouteImport.update({
  id: "/$orgSlug",
  path: "/$orgSlug",
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugTerminalRoute = AppOrgSlugTerminalRouteImport.update({
  id: "/terminal",
  path: "/terminal",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugTeamRoute = AppOrgSlugTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugSshKeysRoute = AppOrgSlugSshKeysRouteImport.update({
  id: "/ssh-keys",
  path: "/ssh-keys",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugSettingsRoute = AppOrgSlugSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugServersRoute = AppOrgSlugServersRouteImport.update({
  id: "/servers",
  path: "/servers",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugRegistriesRoute = AppOrgSlugRegistriesRouteImport.update({
  id: "/registries",
  path: "/registries",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugPlatformRoute = AppOrgSlugPlatformRouteImport.update({
  id: "/platform",
  path: "/platform",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugNotificationsRoute = AppOrgSlugNotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugNetworkingRoute = AppOrgSlugNetworkingRouteImport.update({
  id: "/networking",
  path: "/networking",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugInstanceRoute = AppOrgSlugInstanceRouteImport.update({
  id: "/instance",
  path: "/instance",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugGitProvidersRoute = AppOrgSlugGitProvidersRouteImport.update({
  id: "/git-providers",
  path: "/git-providers",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugFirewallRoute = AppOrgSlugFirewallRouteImport.update({
  id: "/firewall",
  path: "/firewall",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugEdgeLogsRoute = AppOrgSlugEdgeLogsRouteImport.update({
  id: "/edge-logs",
  path: "/edge-logs",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugDockerRoute = AppOrgSlugDockerRouteImport.update({
  id: "/docker",
  path: "/docker",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugBackupsRoute = AppOrgSlugBackupsRouteImport.update({
  id: "/backups",
  path: "/backups",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugAuditRoute = AppOrgSlugAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugApiKeysRoute = AppOrgSlugApiKeysRouteImport.update({
  id: "/api-keys",
  path: "/api-keys",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugProjectSlugLayoutRoute =
  AppOrgSlugProjectSlugLayoutRouteImport.update({
    id: "/$projectSlug",
    path: "/$projectSlug",
    getParentRoute: () => AppOrgSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugIndexRoute =
  AppOrgSlugProjectSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugGithubAppProviderIdRoute =
  AppOrgSlugGithubAppProviderIdRouteImport.update({
    id: "/github-app/$providerId",
    path: "/github-app/$providerId",
    getParentRoute: () => AppOrgSlugLayoutRoute,
  } as any)
const AppOrgSlugGitProvidersProviderIdRoute =
  AppOrgSlugGitProvidersProviderIdRouteImport.update({
    id: "/$providerId",
    path: "/$providerId",
    getParentRoute: () => AppOrgSlugGitProvidersRoute,
  } as any)
const AppOrgSlugProjectSlugVariablesRoute =
  AppOrgSlugProjectSlugVariablesRouteImport.update({
    id: "/variables",
    path: "/variables",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugSettingsRoute =
  AppOrgSlugProjectSlugSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugNetworkingRoute =
  AppOrgSlugProjectSlugNetworkingRouteImport.update({
    id: "/networking",
    path: "/networking",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugMetricsRoute =
  AppOrgSlugProjectSlugMetricsRouteImport.update({
    id: "/metrics",
    path: "/metrics",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugLogsRoute =
  AppOrgSlugProjectSlugLogsRouteImport.update({
    id: "/logs",
    path: "/logs",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugEdgeLogsRoute =
  AppOrgSlugProjectSlugEdgeLogsRouteImport.update({
    id: "/edge-logs",
    path: "/edge-logs",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphLayoutRoute =
  AppOrgSlugProjectSlugGraphLayoutRouteImport.update({
    id: "/graph",
    path: "/graph",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphResourceIdLayoutRoute =
  AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport.update({
    id: "/$resourceId",
    path: "/$resourceId",
    getParentRoute: () => AppOrgSlugProjectSlugGraphLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute =
  AppOrgSlugProjectSlugGraphPreviewPreviewIdRouteImport.update({
    id: "/preview/$previewId",
    path: "/preview/$previewId",
    getParentRoute: () => AppOrgSlugProjectSlugGraphLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute =
  AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport.update({
    id: "/deployment/$deploymentId",
    path: "/deployment/$deploymentId",
    getParentRoute: () => AppOrgSlugProjectSlugGraphResourceIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/device": typeof DeviceRoute
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/$orgSlug": typeof AppOrgSlugLayoutRouteWithChildren
  "/accept-invite/$invitationId": typeof AcceptInviteInvitationIdRoute
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  "/$orgSlug/api-keys": typeof AppOrgSlugApiKeysRoute
  "/$orgSlug/audit": typeof AppOrgSlugAuditRoute
  "/$orgSlug/backups": typeof AppOrgSlugBackupsRoute
  "/$orgSlug/docker": typeof AppOrgSlugDockerRoute
  "/$orgSlug/edge-logs": typeof AppOrgSlugEdgeLogsRoute
  "/$orgSlug/firewall": typeof AppOrgSlugFirewallRoute
  "/$orgSlug/git-providers": typeof AppOrgSlugGitProvidersRouteWithChildren
  "/$orgSlug/instance": typeof AppOrgSlugInstanceRoute
  "/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/$orgSlug/notifications": typeof AppOrgSlugNotificationsRoute
  "/$orgSlug/platform": typeof AppOrgSlugPlatformRoute
  "/$orgSlug/registries": typeof AppOrgSlugRegistriesRoute
  "/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/$orgSlug/ssh-keys": typeof AppOrgSlugSshKeysRoute
  "/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/$orgSlug/": typeof AppOrgSlugIndexRoute
  "/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/edge-logs": typeof AppOrgSlugProjectSlugEdgeLogsRoute
  "/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/$orgSlug/$projectSlug/metrics": typeof AppOrgSlugProjectSlugMetricsRoute
  "/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/$orgSlug/$projectSlug/settings": typeof AppOrgSlugProjectSlugSettingsRoute
  "/$orgSlug/$projectSlug/variables": typeof AppOrgSlugProjectSlugVariablesRoute
  "/$orgSlug/git-providers/$providerId": typeof AppOrgSlugGitProvidersProviderIdRoute
  "/$orgSlug/github-app/$providerId": typeof AppOrgSlugGithubAppProviderIdRoute
  "/$orgSlug/$projectSlug/": typeof AppOrgSlugProjectSlugIndexRoute
  "/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/graph/preview/$previewId": typeof AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute
  "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRoutesByTo {
  "/device": typeof DeviceRoute
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/accept-invite/$invitationId": typeof AcceptInviteInvitationIdRoute
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/": typeof AppIndexRoute
  "/$orgSlug/api-keys": typeof AppOrgSlugApiKeysRoute
  "/$orgSlug/audit": typeof AppOrgSlugAuditRoute
  "/$orgSlug/backups": typeof AppOrgSlugBackupsRoute
  "/$orgSlug/docker": typeof AppOrgSlugDockerRoute
  "/$orgSlug/edge-logs": typeof AppOrgSlugEdgeLogsRoute
  "/$orgSlug/firewall": typeof AppOrgSlugFirewallRoute
  "/$orgSlug/git-providers": typeof AppOrgSlugGitProvidersRouteWithChildren
  "/$orgSlug/instance": typeof AppOrgSlugInstanceRoute
  "/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/$orgSlug/notifications": typeof AppOrgSlugNotificationsRoute
  "/$orgSlug/platform": typeof AppOrgSlugPlatformRoute
  "/$orgSlug/registries": typeof AppOrgSlugRegistriesRoute
  "/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/$orgSlug/ssh-keys": typeof AppOrgSlugSshKeysRoute
  "/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/$orgSlug": typeof AppOrgSlugIndexRoute
  "/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/edge-logs": typeof AppOrgSlugProjectSlugEdgeLogsRoute
  "/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/$orgSlug/$projectSlug/metrics": typeof AppOrgSlugProjectSlugMetricsRoute
  "/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/$orgSlug/$projectSlug/settings": typeof AppOrgSlugProjectSlugSettingsRoute
  "/$orgSlug/$projectSlug/variables": typeof AppOrgSlugProjectSlugVariablesRoute
  "/$orgSlug/git-providers/$providerId": typeof AppOrgSlugGitProvidersProviderIdRoute
  "/$orgSlug/github-app/$providerId": typeof AppOrgSlugGithubAppProviderIdRoute
  "/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugIndexRoute
  "/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/graph/preview/$previewId": typeof AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute
  "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppLayoutRouteWithChildren
  "/device": typeof DeviceRoute
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/_app/$orgSlug": typeof AppOrgSlugLayoutRouteWithChildren
  "/accept-invite/$invitationId": typeof AcceptInviteInvitationIdRoute
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/_app/": typeof AppIndexRoute
  "/_app/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  "/_app/$orgSlug/api-keys": typeof AppOrgSlugApiKeysRoute
  "/_app/$orgSlug/audit": typeof AppOrgSlugAuditRoute
  "/_app/$orgSlug/backups": typeof AppOrgSlugBackupsRoute
  "/_app/$orgSlug/docker": typeof AppOrgSlugDockerRoute
  "/_app/$orgSlug/edge-logs": typeof AppOrgSlugEdgeLogsRoute
  "/_app/$orgSlug/firewall": typeof AppOrgSlugFirewallRoute
  "/_app/$orgSlug/git-providers": typeof AppOrgSlugGitProvidersRouteWithChildren
  "/_app/$orgSlug/instance": typeof AppOrgSlugInstanceRoute
  "/_app/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/_app/$orgSlug/notifications": typeof AppOrgSlugNotificationsRoute
  "/_app/$orgSlug/platform": typeof AppOrgSlugPlatformRoute
  "/_app/$orgSlug/registries": typeof AppOrgSlugRegistriesRoute
  "/_app/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/_app/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/_app/$orgSlug/ssh-keys": typeof AppOrgSlugSshKeysRoute
  "/_app/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/_app/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/_app/$orgSlug/": typeof AppOrgSlugIndexRoute
  "/_app/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/_app/$orgSlug/$projectSlug/edge-logs": typeof AppOrgSlugProjectSlugEdgeLogsRoute
  "/_app/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/_app/$orgSlug/$projectSlug/metrics": typeof AppOrgSlugProjectSlugMetricsRoute
  "/_app/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/_app/$orgSlug/$projectSlug/settings": typeof AppOrgSlugProjectSlugSettingsRoute
  "/_app/$orgSlug/$projectSlug/variables": typeof AppOrgSlugProjectSlugVariablesRoute
  "/_app/$orgSlug/git-providers/$providerId": typeof AppOrgSlugGitProvidersProviderIdRoute
  "/_app/$orgSlug/github-app/$providerId": typeof AppOrgSlugGithubAppProviderIdRoute
  "/_app/$orgSlug/$projectSlug/": typeof AppOrgSlugProjectSlugIndexRoute
  "/_app/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/_app/$orgSlug/$projectSlug/graph/preview/$previewId": typeof AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute
  "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/device"
    | "/sign-in"
    | "/terminal"
    | "/$orgSlug"
    | "/accept-invite/$invitationId"
    | "/onboarding/create-organization"
    | "/$orgSlug/$projectSlug"
    | "/$orgSlug/api-keys"
    | "/$orgSlug/audit"
    | "/$orgSlug/backups"
    | "/$orgSlug/docker"
    | "/$orgSlug/edge-logs"
    | "/$orgSlug/firewall"
    | "/$orgSlug/git-providers"
    | "/$orgSlug/instance"
    | "/$orgSlug/networking"
    | "/$orgSlug/notifications"
    | "/$orgSlug/platform"
    | "/$orgSlug/registries"
    | "/$orgSlug/servers"
    | "/$orgSlug/settings"
    | "/$orgSlug/ssh-keys"
    | "/$orgSlug/team"
    | "/$orgSlug/terminal"
    | "/$orgSlug/"
    | "/$orgSlug/$projectSlug/graph"
    | "/$orgSlug/$projectSlug/edge-logs"
    | "/$orgSlug/$projectSlug/logs"
    | "/$orgSlug/$projectSlug/metrics"
    | "/$orgSlug/$projectSlug/networking"
    | "/$orgSlug/$projectSlug/settings"
    | "/$orgSlug/$projectSlug/variables"
    | "/$orgSlug/git-providers/$providerId"
    | "/$orgSlug/github-app/$providerId"
    | "/$orgSlug/$projectSlug/"
    | "/$orgSlug/$projectSlug/graph/$resourceId"
    | "/$orgSlug/$projectSlug/graph/preview/$previewId"
    | "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/device"
    | "/sign-in"
    | "/terminal"
    | "/accept-invite/$invitationId"
    | "/onboarding/create-organization"
    | "/"
    | "/$orgSlug/api-keys"
    | "/$orgSlug/audit"
    | "/$orgSlug/backups"
    | "/$orgSlug/docker"
    | "/$orgSlug/edge-logs"
    | "/$orgSlug/firewall"
    | "/$orgSlug/git-providers"
    | "/$orgSlug/instance"
    | "/$orgSlug/networking"
    | "/$orgSlug/notifications"
    | "/$orgSlug/platform"
    | "/$orgSlug/registries"
    | "/$orgSlug/servers"
    | "/$orgSlug/settings"
    | "/$orgSlug/ssh-keys"
    | "/$orgSlug/team"
    | "/$orgSlug/terminal"
    | "/$orgSlug"
    | "/$orgSlug/$projectSlug/graph"
    | "/$orgSlug/$projectSlug/edge-logs"
    | "/$orgSlug/$projectSlug/logs"
    | "/$orgSlug/$projectSlug/metrics"
    | "/$orgSlug/$projectSlug/networking"
    | "/$orgSlug/$projectSlug/settings"
    | "/$orgSlug/$projectSlug/variables"
    | "/$orgSlug/git-providers/$providerId"
    | "/$orgSlug/github-app/$providerId"
    | "/$orgSlug/$projectSlug"
    | "/$orgSlug/$projectSlug/graph/$resourceId"
    | "/$orgSlug/$projectSlug/graph/preview/$previewId"
    | "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  id:
    | "__root__"
    | "/_app"
    | "/device"
    | "/sign-in"
    | "/terminal"
    | "/_app/$orgSlug"
    | "/accept-invite/$invitationId"
    | "/onboarding/create-organization"
    | "/_app/"
    | "/_app/$orgSlug/$projectSlug"
    | "/_app/$orgSlug/api-keys"
    | "/_app/$orgSlug/audit"
    | "/_app/$orgSlug/backups"
    | "/_app/$orgSlug/docker"
    | "/_app/$orgSlug/edge-logs"
    | "/_app/$orgSlug/firewall"
    | "/_app/$orgSlug/git-providers"
    | "/_app/$orgSlug/instance"
    | "/_app/$orgSlug/networking"
    | "/_app/$orgSlug/notifications"
    | "/_app/$orgSlug/platform"
    | "/_app/$orgSlug/registries"
    | "/_app/$orgSlug/servers"
    | "/_app/$orgSlug/settings"
    | "/_app/$orgSlug/ssh-keys"
    | "/_app/$orgSlug/team"
    | "/_app/$orgSlug/terminal"
    | "/_app/$orgSlug/"
    | "/_app/$orgSlug/$projectSlug/graph"
    | "/_app/$orgSlug/$projectSlug/edge-logs"
    | "/_app/$orgSlug/$projectSlug/logs"
    | "/_app/$orgSlug/$projectSlug/metrics"
    | "/_app/$orgSlug/$projectSlug/networking"
    | "/_app/$orgSlug/$projectSlug/settings"
    | "/_app/$orgSlug/$projectSlug/variables"
    | "/_app/$orgSlug/git-providers/$providerId"
    | "/_app/$orgSlug/github-app/$providerId"
    | "/_app/$orgSlug/$projectSlug/"
    | "/_app/$orgSlug/$projectSlug/graph/$resourceId"
    | "/_app/$orgSlug/$projectSlug/graph/preview/$previewId"
    | "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  SignInRoute: typeof SignInRoute
  TerminalRoute: typeof TerminalRoute
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
  OnboardingCreateOrganizationRoute: typeof OnboardingCreateOrganizationRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terminal": {
      id: "/terminal"
      path: "/terminal"
      fullPath: "/terminal"
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/device": {
      id: "/device"
      path: "/device"
      fullPath: "/device"
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    "/onboarding/create-organization": {
      id: "/onboarding/create-organization"
      path: "/onboarding/create-organization"
      fullPath: "/onboarding/create-organization"
      preLoaderRoute: typeof OnboardingCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accept-invite/$invitationId": {
      id: "/accept-invite/$invitationId"
      path: "/accept-invite/$invitationId"
      fullPath: "/accept-invite/$invitationId"
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/$orgSlug": {
      id: "/_app/$orgSlug"
      path: "/$orgSlug"
      fullPath: "/$orgSlug"
      preLoaderRoute: typeof AppOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    "/_app/$orgSlug/": {
      id: "/_app/$orgSlug/"
      path: "/"
      fullPath: "/$orgSlug/"
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/terminal": {
      id: "/_app/$orgSlug/terminal"
      path: "/terminal"
      fullPath: "/$orgSlug/terminal"
      preLoaderRoute: typeof AppOrgSlugTerminalRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/team": {
      id: "/_app/$orgSlug/team"
      path: "/team"
      fullPath: "/$orgSlug/team"
      preLoaderRoute: typeof AppOrgSlugTeamRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/ssh-keys": {
      id: "/_app/$orgSlug/ssh-keys"
      path: "/ssh-keys"
      fullPath: "/$orgSlug/ssh-keys"
      preLoaderRoute: typeof AppOrgSlugSshKeysRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/settings": {
      id: "/_app/$orgSlug/settings"
      path: "/settings"
      fullPath: "/$orgSlug/settings"
      preLoaderRoute: typeof AppOrgSlugSettingsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/servers": {
      id: "/_app/$orgSlug/servers"
      path: "/servers"
      fullPath: "/$orgSlug/servers"
      preLoaderRoute: typeof AppOrgSlugServersRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/registries": {
      id: "/_app/$orgSlug/registries"
      path: "/registries"
      fullPath: "/$orgSlug/registries"
      preLoaderRoute: typeof AppOrgSlugRegistriesRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/platform": {
      id: "/_app/$orgSlug/platform"
      path: "/platform"
      fullPath: "/$orgSlug/platform"
      preLoaderRoute: typeof AppOrgSlugPlatformRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/notifications": {
      id: "/_app/$orgSlug/notifications"
      path: "/notifications"
      fullPath: "/$orgSlug/notifications"
      preLoaderRoute: typeof AppOrgSlugNotificationsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/networking": {
      id: "/_app/$orgSlug/networking"
      path: "/networking"
      fullPath: "/$orgSlug/networking"
      preLoaderRoute: typeof AppOrgSlugNetworkingRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/instance": {
      id: "/_app/$orgSlug/instance"
      path: "/instance"
      fullPath: "/$orgSlug/instance"
      preLoaderRoute: typeof AppOrgSlugInstanceRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/git-providers": {
      id: "/_app/$orgSlug/git-providers"
      path: "/git-providers"
      fullPath: "/$orgSlug/git-providers"
      preLoaderRoute: typeof AppOrgSlugGitProvidersRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/firewall": {
      id: "/_app/$orgSlug/firewall"
      path: "/firewall"
      fullPath: "/$orgSlug/firewall"
      preLoaderRoute: typeof AppOrgSlugFirewallRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/edge-logs": {
      id: "/_app/$orgSlug/edge-logs"
      path: "/edge-logs"
      fullPath: "/$orgSlug/edge-logs"
      preLoaderRoute: typeof AppOrgSlugEdgeLogsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/docker": {
      id: "/_app/$orgSlug/docker"
      path: "/docker"
      fullPath: "/$orgSlug/docker"
      preLoaderRoute: typeof AppOrgSlugDockerRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/backups": {
      id: "/_app/$orgSlug/backups"
      path: "/backups"
      fullPath: "/$orgSlug/backups"
      preLoaderRoute: typeof AppOrgSlugBackupsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/audit": {
      id: "/_app/$orgSlug/audit"
      path: "/audit"
      fullPath: "/$orgSlug/audit"
      preLoaderRoute: typeof AppOrgSlugAuditRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/api-keys": {
      id: "/_app/$orgSlug/api-keys"
      path: "/api-keys"
      fullPath: "/$orgSlug/api-keys"
      preLoaderRoute: typeof AppOrgSlugApiKeysRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug": {
      id: "/_app/$orgSlug/$projectSlug"
      path: "/$projectSlug"
      fullPath: "/$orgSlug/$projectSlug"
      preLoaderRoute: typeof AppOrgSlugProjectSlugLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/": {
      id: "/_app/$orgSlug/$projectSlug/"
      path: "/"
      fullPath: "/$orgSlug/$projectSlug/"
      preLoaderRoute: typeof AppOrgSlugProjectSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/github-app/$providerId": {
      id: "/_app/$orgSlug/github-app/$providerId"
      path: "/github-app/$providerId"
      fullPath: "/$orgSlug/github-app/$providerId"
      preLoaderRoute: typeof AppOrgSlugGithubAppProviderIdRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/git-providers/$providerId": {
      id: "/_app/$orgSlug/git-providers/$providerId"
      path: "/$providerId"
      fullPath: "/$orgSlug/git-providers/$providerId"
      preLoaderRoute: typeof AppOrgSlugGitProvidersProviderIdRouteImport
      parentRoute: typeof AppOrgSlugGitProvidersRoute
    }
    "/_app/$orgSlug/$projectSlug/variables": {
      id: "/_app/$orgSlug/$projectSlug/variables"
      path: "/variables"
      fullPath: "/$orgSlug/$projectSlug/variables"
      preLoaderRoute: typeof AppOrgSlugProjectSlugVariablesRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/settings": {
      id: "/_app/$orgSlug/$projectSlug/settings"
      path: "/settings"
      fullPath: "/$orgSlug/$projectSlug/settings"
      preLoaderRoute: typeof AppOrgSlugProjectSlugSettingsRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/networking": {
      id: "/_app/$orgSlug/$projectSlug/networking"
      path: "/networking"
      fullPath: "/$orgSlug/$projectSlug/networking"
      preLoaderRoute: typeof AppOrgSlugProjectSlugNetworkingRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/metrics": {
      id: "/_app/$orgSlug/$projectSlug/metrics"
      path: "/metrics"
      fullPath: "/$orgSlug/$projectSlug/metrics"
      preLoaderRoute: typeof AppOrgSlugProjectSlugMetricsRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/logs": {
      id: "/_app/$orgSlug/$projectSlug/logs"
      path: "/logs"
      fullPath: "/$orgSlug/$projectSlug/logs"
      preLoaderRoute: typeof AppOrgSlugProjectSlugLogsRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/edge-logs": {
      id: "/_app/$orgSlug/$projectSlug/edge-logs"
      path: "/edge-logs"
      fullPath: "/$orgSlug/$projectSlug/edge-logs"
      preLoaderRoute: typeof AppOrgSlugProjectSlugEdgeLogsRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph": {
      id: "/_app/$orgSlug/$projectSlug/graph"
      path: "/graph"
      fullPath: "/$orgSlug/$projectSlug/graph"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphLayoutRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph/$resourceId": {
      id: "/_app/$orgSlug/$projectSlug/graph/$resourceId"
      path: "/$resourceId"
      fullPath: "/$orgSlug/$projectSlug/graph/$resourceId"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugGraphLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph/preview/$previewId": {
      id: "/_app/$orgSlug/$projectSlug/graph/preview/$previewId"
      path: "/preview/$previewId"
      fullPath: "/$orgSlug/$projectSlug/graph/preview/$previewId"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphPreviewPreviewIdRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugGraphLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": {
      id: "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
      path: "/deployment/$deploymentId"
      fullPath: "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRoute
    }
  }
}

interface AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute: typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}

const AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren: AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute:
      AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute,
  }

const AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren =
  AppOrgSlugProjectSlugGraphResourceIdLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren,
  )

interface AppOrgSlugProjectSlugGraphLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphResourceIdLayoutRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute: typeof AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute
}

const AppOrgSlugProjectSlugGraphLayoutRouteChildren: AppOrgSlugProjectSlugGraphLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphResourceIdLayoutRoute:
      AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren,
    AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute:
      AppOrgSlugProjectSlugGraphPreviewPreviewIdRoute,
  }

const AppOrgSlugProjectSlugGraphLayoutRouteWithChildren =
  AppOrgSlugProjectSlugGraphLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugGraphLayoutRouteChildren,
  )

interface AppOrgSlugProjectSlugLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphLayoutRoute: typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  AppOrgSlugProjectSlugEdgeLogsRoute: typeof AppOrgSlugProjectSlugEdgeLogsRoute
  AppOrgSlugProjectSlugLogsRoute: typeof AppOrgSlugProjectSlugLogsRoute
  AppOrgSlugProjectSlugMetricsRoute: typeof AppOrgSlugProjectSlugMetricsRoute
  AppOrgSlugProjectSlugNetworkingRoute: typeof AppOrgSlugProjectSlugNetworkingRoute
  AppOrgSlugProjectSlugSettingsRoute: typeof AppOrgSlugProjectSlugSettingsRoute
  AppOrgSlugProjectSlugVariablesRoute: typeof AppOrgSlugProjectSlugVariablesRoute
  AppOrgSlugProjectSlugIndexRoute: typeof AppOrgSlugProjectSlugIndexRoute
}

const AppOrgSlugProjectSlugLayoutRouteChildren: AppOrgSlugProjectSlugLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphLayoutRoute:
      AppOrgSlugProjectSlugGraphLayoutRouteWithChildren,
    AppOrgSlugProjectSlugEdgeLogsRoute: AppOrgSlugProjectSlugEdgeLogsRoute,
    AppOrgSlugProjectSlugLogsRoute: AppOrgSlugProjectSlugLogsRoute,
    AppOrgSlugProjectSlugMetricsRoute: AppOrgSlugProjectSlugMetricsRoute,
    AppOrgSlugProjectSlugNetworkingRoute: AppOrgSlugProjectSlugNetworkingRoute,
    AppOrgSlugProjectSlugSettingsRoute: AppOrgSlugProjectSlugSettingsRoute,
    AppOrgSlugProjectSlugVariablesRoute: AppOrgSlugProjectSlugVariablesRoute,
    AppOrgSlugProjectSlugIndexRoute: AppOrgSlugProjectSlugIndexRoute,
  }

const AppOrgSlugProjectSlugLayoutRouteWithChildren =
  AppOrgSlugProjectSlugLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugLayoutRouteChildren,
  )

interface AppOrgSlugGitProvidersRouteChildren {
  AppOrgSlugGitProvidersProviderIdRoute: typeof AppOrgSlugGitProvidersProviderIdRoute
}

const AppOrgSlugGitProvidersRouteChildren: AppOrgSlugGitProvidersRouteChildren =
  {
    AppOrgSlugGitProvidersProviderIdRoute:
      AppOrgSlugGitProvidersProviderIdRoute,
  }

const AppOrgSlugGitProvidersRouteWithChildren =
  AppOrgSlugGitProvidersRoute._addFileChildren(
    AppOrgSlugGitProvidersRouteChildren,
  )

interface AppOrgSlugLayoutRouteChildren {
  AppOrgSlugProjectSlugLayoutRoute: typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  AppOrgSlugApiKeysRoute: typeof AppOrgSlugApiKeysRoute
  AppOrgSlugAuditRoute: typeof AppOrgSlugAuditRoute
  AppOrgSlugBackupsRoute: typeof AppOrgSlugBackupsRoute
  AppOrgSlugDockerRoute: typeof AppOrgSlugDockerRoute
  AppOrgSlugEdgeLogsRoute: typeof AppOrgSlugEdgeLogsRoute
  AppOrgSlugFirewallRoute: typeof AppOrgSlugFirewallRoute
  AppOrgSlugGitProvidersRoute: typeof AppOrgSlugGitProvidersRouteWithChildren
  AppOrgSlugInstanceRoute: typeof AppOrgSlugInstanceRoute
  AppOrgSlugNetworkingRoute: typeof AppOrgSlugNetworkingRoute
  AppOrgSlugNotificationsRoute: typeof AppOrgSlugNotificationsRoute
  AppOrgSlugPlatformRoute: typeof AppOrgSlugPlatformRoute
  AppOrgSlugRegistriesRoute: typeof AppOrgSlugRegistriesRoute
  AppOrgSlugServersRoute: typeof AppOrgSlugServersRoute
  AppOrgSlugSettingsRoute: typeof AppOrgSlugSettingsRoute
  AppOrgSlugSshKeysRoute: typeof AppOrgSlugSshKeysRoute
  AppOrgSlugTeamRoute: typeof AppOrgSlugTeamRoute
  AppOrgSlugTerminalRoute: typeof AppOrgSlugTerminalRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
  AppOrgSlugGithubAppProviderIdRoute: typeof AppOrgSlugGithubAppProviderIdRoute
}

const AppOrgSlugLayoutRouteChildren: AppOrgSlugLayoutRouteChildren = {
  AppOrgSlugProjectSlugLayoutRoute:
    AppOrgSlugProjectSlugLayoutRouteWithChildren,
  AppOrgSlugApiKeysRoute: AppOrgSlugApiKeysRoute,
  AppOrgSlugAuditRoute: AppOrgSlugAuditRoute,
  AppOrgSlugBackupsRoute: AppOrgSlugBackupsRoute,
  AppOrgSlugDockerRoute: AppOrgSlugDockerRoute,
  AppOrgSlugEdgeLogsRoute: AppOrgSlugEdgeLogsRoute,
  AppOrgSlugFirewallRoute: AppOrgSlugFirewallRoute,
  AppOrgSlugGitProvidersRoute: AppOrgSlugGitProvidersRouteWithChildren,
  AppOrgSlugInstanceRoute: AppOrgSlugInstanceRoute,
  AppOrgSlugNetworkingRoute: AppOrgSlugNetworkingRoute,
  AppOrgSlugNotificationsRoute: AppOrgSlugNotificationsRoute,
  AppOrgSlugPlatformRoute: AppOrgSlugPlatformRoute,
  AppOrgSlugRegistriesRoute: AppOrgSlugRegistriesRoute,
  AppOrgSlugServersRoute: AppOrgSlugServersRoute,
  AppOrgSlugSettingsRoute: AppOrgSlugSettingsRoute,
  AppOrgSlugSshKeysRoute: AppOrgSlugSshKeysRoute,
  AppOrgSlugTeamRoute: AppOrgSlugTeamRoute,
  AppOrgSlugTerminalRoute: AppOrgSlugTerminalRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
  AppOrgSlugGithubAppProviderIdRoute: AppOrgSlugGithubAppProviderIdRoute,
}

const AppOrgSlugLayoutRouteWithChildren =
  AppOrgSlugLayoutRoute._addFileChildren(AppOrgSlugLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppOrgSlugLayoutRoute: typeof AppOrgSlugLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppOrgSlugLayoutRoute: AppOrgSlugLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  DeviceRoute: DeviceRoute,
  SignInRoute: SignInRoute,
  TerminalRoute: TerminalRoute,
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
  OnboardingCreateOrganizationRoute: OnboardingCreateOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
