/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as AuthLayoutRouteImport } from './routes/_auth/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard/projects/index'
import { Route as DashboardProjectsProjectIdLayoutRouteImport } from './routes/_dashboard/projects/$projectId/layout'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard/projects/$projectId/index'
import { Route as DashboardProjectsProjectIdVolumeVolumeRouteImport } from './routes/_dashboard/projects/$projectId/volume/$volume'
import { Route as DashboardProjectsProjectIdServiceServiceIdRouteImport } from './routes/_dashboard/projects/$projectId/service/$serviceId'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProjectsProjectIdLayoutRoute =
  DashboardProjectsProjectIdLayoutRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdLayoutRoute,
  } as any)
const DashboardProjectsProjectIdVolumeVolumeRoute =
  DashboardProjectsProjectIdVolumeVolumeRouteImport.update({
    id: '/volume/$volume',
    path: '/volume/$volume',
    getParentRoute: () => DashboardProjectsProjectIdLayoutRoute,
  } as any)
const DashboardProjectsProjectIdServiceServiceIdRoute =
  DashboardProjectsProjectIdServiceServiceIdRouteImport.update({
    id: '/service/$serviceId',
    path: '/service/$serviceId',
    getParentRoute: () => DashboardProjectsProjectIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdLayoutRouteWithChildren
  '/projects/': typeof DashboardProjectsIndexRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/service/$serviceId': typeof DashboardProjectsProjectIdServiceServiceIdRoute
  '/projects/$projectId/volume/$volume': typeof DashboardProjectsProjectIdVolumeVolumeRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/projects/$projectId/service/$serviceId': typeof DashboardProjectsProjectIdServiceServiceIdRoute
  '/projects/$projectId/volume/$volume': typeof DashboardProjectsProjectIdVolumeVolumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdLayoutRouteWithChildren
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/projects/$projectId/service/$serviceId': typeof DashboardProjectsProjectIdServiceServiceIdRoute
  '/_dashboard/projects/$projectId/volume/$volume': typeof DashboardProjectsProjectIdVolumeVolumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/'
    | '/projects/$projectId/service/$serviceId'
    | '/projects/$projectId/volume/$volume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/service/$serviceId'
    | '/projects/$projectId/volume/$volume'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_dashboard/'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/projects/'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/projects/$projectId/service/$serviceId'
    | '/_dashboard/projects/$projectId/volume/$volume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdLayoutRoute
    }
    '/_dashboard/projects/$projectId/volume/$volume': {
      id: '/_dashboard/projects/$projectId/volume/$volume'
      path: '/volume/$volume'
      fullPath: '/projects/$projectId/volume/$volume'
      preLoaderRoute: typeof DashboardProjectsProjectIdVolumeVolumeRouteImport
      parentRoute: typeof DashboardProjectsProjectIdLayoutRoute
    }
    '/_dashboard/projects/$projectId/service/$serviceId': {
      id: '/_dashboard/projects/$projectId/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/projects/$projectId/service/$serviceId'
      preLoaderRoute: typeof DashboardProjectsProjectIdServiceServiceIdRouteImport
      parentRoute: typeof DashboardProjectsProjectIdLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface DashboardProjectsProjectIdLayoutRouteChildren {
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
  DashboardProjectsProjectIdServiceServiceIdRoute: typeof DashboardProjectsProjectIdServiceServiceIdRoute
  DashboardProjectsProjectIdVolumeVolumeRoute: typeof DashboardProjectsProjectIdVolumeVolumeRoute
}

const DashboardProjectsProjectIdLayoutRouteChildren: DashboardProjectsProjectIdLayoutRouteChildren =
  {
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
    DashboardProjectsProjectIdServiceServiceIdRoute:
      DashboardProjectsProjectIdServiceServiceIdRoute,
    DashboardProjectsProjectIdVolumeVolumeRoute:
      DashboardProjectsProjectIdVolumeVolumeRoute,
  }

const DashboardProjectsProjectIdLayoutRouteWithChildren =
  DashboardProjectsProjectIdLayoutRoute._addFileChildren(
    DashboardProjectsProjectIdLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsProjectIdLayoutRoute: typeof DashboardProjectsProjectIdLayoutRouteWithChildren
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsProjectIdLayoutRoute:
    DashboardProjectsProjectIdLayoutRouteWithChildren,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
