/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TerminalRouteImport } from "./routes/terminal"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as AppLayoutRouteImport } from "./routes/_app/layout"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as OnboardingCreateOrganizationRouteImport } from "./routes/onboarding/create-organization"
import { Route as AppOrgSlugLayoutRouteImport } from "./routes/_app/$orgSlug/layout"
import { Route as AppOrgSlugIndexRouteImport } from "./routes/_app/$orgSlug/index"
import { Route as AppOrgSlugTerminalRouteImport } from "./routes/_app/$orgSlug/terminal"
import { Route as AppOrgSlugTeamRouteImport } from "./routes/_app/$orgSlug/team"
import { Route as AppOrgSlugSettingsRouteImport } from "./routes/_app/$orgSlug/settings"
import { Route as AppOrgSlugServersRouteImport } from "./routes/_app/$orgSlug/servers"
import { Route as AppOrgSlugNetworkingRouteImport } from "./routes/_app/$orgSlug/networking"
import { Route as AppOrgSlugProjectSlugLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/layout"
import { Route as AppOrgSlugProjectSlugIndexRouteImport } from "./routes/_app/$orgSlug/$projectSlug/index"
import { Route as AppOrgSlugProjectSlugNewResourceRouteImport } from "./routes/_app/$orgSlug/$projectSlug/new-resource"
import { Route as AppOrgSlugProjectSlugNetworkingRouteImport } from "./routes/_app/$orgSlug/$projectSlug/networking"
import { Route as AppOrgSlugProjectSlugLogsRouteImport } from "./routes/_app/$orgSlug/$projectSlug/logs"
import { Route as AppOrgSlugProjectSlugGraphLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/layout"
import { Route as AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/$resourceId/layout"
import { Route as AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport } from "./routes/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"

const TerminalRoute = TerminalRouteImport.update({
  id: "/terminal",
  path: "/terminal",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppLayoutRoute,
} as any)
const OnboardingCreateOrganizationRoute =
  OnboardingCreateOrganizationRouteImport.update({
    id: "/onboarding/create-organization",
    path: "/onboarding/create-organization",
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrgSlugLayoutRoute = AppOrgSlugLayoutRouteImport.update({
  id: "/$orgSlug",
  path: "/$orgSlug",
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrgSlugIndexRoute = AppOrgSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugTerminalRoute = AppOrgSlugTerminalRouteImport.update({
  id: "/terminal",
  path: "/terminal",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugTeamRoute = AppOrgSlugTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugSettingsRoute = AppOrgSlugSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugServersRoute = AppOrgSlugServersRouteImport.update({
  id: "/servers",
  path: "/servers",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugNetworkingRoute = AppOrgSlugNetworkingRouteImport.update({
  id: "/networking",
  path: "/networking",
  getParentRoute: () => AppOrgSlugLayoutRoute,
} as any)
const AppOrgSlugProjectSlugLayoutRoute =
  AppOrgSlugProjectSlugLayoutRouteImport.update({
    id: "/$projectSlug",
    path: "/$projectSlug",
    getParentRoute: () => AppOrgSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugIndexRoute =
  AppOrgSlugProjectSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugNewResourceRoute =
  AppOrgSlugProjectSlugNewResourceRouteImport.update({
    id: "/new-resource",
    path: "/new-resource",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugNetworkingRoute =
  AppOrgSlugProjectSlugNetworkingRouteImport.update({
    id: "/networking",
    path: "/networking",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugLogsRoute =
  AppOrgSlugProjectSlugLogsRouteImport.update({
    id: "/logs",
    path: "/logs",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphLayoutRoute =
  AppOrgSlugProjectSlugGraphLayoutRouteImport.update({
    id: "/graph",
    path: "/graph",
    getParentRoute: () => AppOrgSlugProjectSlugLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphResourceIdLayoutRoute =
  AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport.update({
    id: "/$resourceId",
    path: "/$resourceId",
    getParentRoute: () => AppOrgSlugProjectSlugGraphLayoutRoute,
  } as any)
const AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute =
  AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport.update({
    id: "/deployment/$deploymentId",
    path: "/deployment/$deploymentId",
    getParentRoute: () => AppOrgSlugProjectSlugGraphResourceIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/$orgSlug": typeof AppOrgSlugLayoutRouteWithChildren
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  "/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/$orgSlug/": typeof AppOrgSlugIndexRoute
  "/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/$orgSlug/$projectSlug/new-resource": typeof AppOrgSlugProjectSlugNewResourceRoute
  "/$orgSlug/$projectSlug/": typeof AppOrgSlugProjectSlugIndexRoute
  "/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRoutesByTo {
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/": typeof AppIndexRoute
  "/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/$orgSlug": typeof AppOrgSlugIndexRoute
  "/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/$orgSlug/$projectSlug/new-resource": typeof AppOrgSlugProjectSlugNewResourceRoute
  "/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugIndexRoute
  "/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppLayoutRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/terminal": typeof TerminalRoute
  "/_app/$orgSlug": typeof AppOrgSlugLayoutRouteWithChildren
  "/onboarding/create-organization": typeof OnboardingCreateOrganizationRoute
  "/_app/": typeof AppIndexRoute
  "/_app/$orgSlug/$projectSlug": typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  "/_app/$orgSlug/networking": typeof AppOrgSlugNetworkingRoute
  "/_app/$orgSlug/servers": typeof AppOrgSlugServersRoute
  "/_app/$orgSlug/settings": typeof AppOrgSlugSettingsRoute
  "/_app/$orgSlug/team": typeof AppOrgSlugTeamRoute
  "/_app/$orgSlug/terminal": typeof AppOrgSlugTerminalRoute
  "/_app/$orgSlug/": typeof AppOrgSlugIndexRoute
  "/_app/$orgSlug/$projectSlug/graph": typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  "/_app/$orgSlug/$projectSlug/logs": typeof AppOrgSlugProjectSlugLogsRoute
  "/_app/$orgSlug/$projectSlug/networking": typeof AppOrgSlugProjectSlugNetworkingRoute
  "/_app/$orgSlug/$projectSlug/new-resource": typeof AppOrgSlugProjectSlugNewResourceRoute
  "/_app/$orgSlug/$projectSlug/": typeof AppOrgSlugProjectSlugIndexRoute
  "/_app/$orgSlug/$projectSlug/graph/$resourceId": typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
  "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/sign-in"
    | "/terminal"
    | "/$orgSlug"
    | "/onboarding/create-organization"
    | "/$orgSlug/$projectSlug"
    | "/$orgSlug/networking"
    | "/$orgSlug/servers"
    | "/$orgSlug/settings"
    | "/$orgSlug/team"
    | "/$orgSlug/terminal"
    | "/$orgSlug/"
    | "/$orgSlug/$projectSlug/graph"
    | "/$orgSlug/$projectSlug/logs"
    | "/$orgSlug/$projectSlug/networking"
    | "/$orgSlug/$projectSlug/new-resource"
    | "/$orgSlug/$projectSlug/"
    | "/$orgSlug/$projectSlug/graph/$resourceId"
    | "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/sign-in"
    | "/terminal"
    | "/onboarding/create-organization"
    | "/"
    | "/$orgSlug/networking"
    | "/$orgSlug/servers"
    | "/$orgSlug/settings"
    | "/$orgSlug/team"
    | "/$orgSlug/terminal"
    | "/$orgSlug"
    | "/$orgSlug/$projectSlug/graph"
    | "/$orgSlug/$projectSlug/logs"
    | "/$orgSlug/$projectSlug/networking"
    | "/$orgSlug/$projectSlug/new-resource"
    | "/$orgSlug/$projectSlug"
    | "/$orgSlug/$projectSlug/graph/$resourceId"
    | "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  id:
    | "__root__"
    | "/_app"
    | "/sign-in"
    | "/terminal"
    | "/_app/$orgSlug"
    | "/onboarding/create-organization"
    | "/_app/"
    | "/_app/$orgSlug/$projectSlug"
    | "/_app/$orgSlug/networking"
    | "/_app/$orgSlug/servers"
    | "/_app/$orgSlug/settings"
    | "/_app/$orgSlug/team"
    | "/_app/$orgSlug/terminal"
    | "/_app/$orgSlug/"
    | "/_app/$orgSlug/$projectSlug/graph"
    | "/_app/$orgSlug/$projectSlug/logs"
    | "/_app/$orgSlug/$projectSlug/networking"
    | "/_app/$orgSlug/$projectSlug/new-resource"
    | "/_app/$orgSlug/$projectSlug/"
    | "/_app/$orgSlug/$projectSlug/graph/$resourceId"
    | "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  SignInRoute: typeof SignInRoute
  TerminalRoute: typeof TerminalRoute
  OnboardingCreateOrganizationRoute: typeof OnboardingCreateOrganizationRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terminal": {
      id: "/terminal"
      path: "/terminal"
      fullPath: "/terminal"
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    "/onboarding/create-organization": {
      id: "/onboarding/create-organization"
      path: "/onboarding/create-organization"
      fullPath: "/onboarding/create-organization"
      preLoaderRoute: typeof OnboardingCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/$orgSlug": {
      id: "/_app/$orgSlug"
      path: "/$orgSlug"
      fullPath: "/$orgSlug"
      preLoaderRoute: typeof AppOrgSlugLayoutRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    "/_app/$orgSlug/": {
      id: "/_app/$orgSlug/"
      path: "/"
      fullPath: "/$orgSlug/"
      preLoaderRoute: typeof AppOrgSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/terminal": {
      id: "/_app/$orgSlug/terminal"
      path: "/terminal"
      fullPath: "/$orgSlug/terminal"
      preLoaderRoute: typeof AppOrgSlugTerminalRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/team": {
      id: "/_app/$orgSlug/team"
      path: "/team"
      fullPath: "/$orgSlug/team"
      preLoaderRoute: typeof AppOrgSlugTeamRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/settings": {
      id: "/_app/$orgSlug/settings"
      path: "/settings"
      fullPath: "/$orgSlug/settings"
      preLoaderRoute: typeof AppOrgSlugSettingsRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/servers": {
      id: "/_app/$orgSlug/servers"
      path: "/servers"
      fullPath: "/$orgSlug/servers"
      preLoaderRoute: typeof AppOrgSlugServersRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/networking": {
      id: "/_app/$orgSlug/networking"
      path: "/networking"
      fullPath: "/$orgSlug/networking"
      preLoaderRoute: typeof AppOrgSlugNetworkingRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug": {
      id: "/_app/$orgSlug/$projectSlug"
      path: "/$projectSlug"
      fullPath: "/$orgSlug/$projectSlug"
      preLoaderRoute: typeof AppOrgSlugProjectSlugLayoutRouteImport
      parentRoute: typeof AppOrgSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/": {
      id: "/_app/$orgSlug/$projectSlug/"
      path: "/"
      fullPath: "/$orgSlug/$projectSlug/"
      preLoaderRoute: typeof AppOrgSlugProjectSlugIndexRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/new-resource": {
      id: "/_app/$orgSlug/$projectSlug/new-resource"
      path: "/new-resource"
      fullPath: "/$orgSlug/$projectSlug/new-resource"
      preLoaderRoute: typeof AppOrgSlugProjectSlugNewResourceRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/networking": {
      id: "/_app/$orgSlug/$projectSlug/networking"
      path: "/networking"
      fullPath: "/$orgSlug/$projectSlug/networking"
      preLoaderRoute: typeof AppOrgSlugProjectSlugNetworkingRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/logs": {
      id: "/_app/$orgSlug/$projectSlug/logs"
      path: "/logs"
      fullPath: "/$orgSlug/$projectSlug/logs"
      preLoaderRoute: typeof AppOrgSlugProjectSlugLogsRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph": {
      id: "/_app/$orgSlug/$projectSlug/graph"
      path: "/graph"
      fullPath: "/$orgSlug/$projectSlug/graph"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphLayoutRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph/$resourceId": {
      id: "/_app/$orgSlug/$projectSlug/graph/$resourceId"
      path: "/$resourceId"
      fullPath: "/$orgSlug/$projectSlug/graph/$resourceId"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugGraphLayoutRoute
    }
    "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId": {
      id: "/_app/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
      path: "/deployment/$deploymentId"
      fullPath: "/$orgSlug/$projectSlug/graph/$resourceId/deployment/$deploymentId"
      preLoaderRoute: typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRouteImport
      parentRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRoute
    }
  }
}

interface AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute: typeof AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute
}

const AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren: AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute:
      AppOrgSlugProjectSlugGraphResourceIdDeploymentDeploymentIdRoute,
  }

const AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren =
  AppOrgSlugProjectSlugGraphResourceIdLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugGraphResourceIdLayoutRouteChildren,
  )

interface AppOrgSlugProjectSlugGraphLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphResourceIdLayoutRoute: typeof AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren
}

const AppOrgSlugProjectSlugGraphLayoutRouteChildren: AppOrgSlugProjectSlugGraphLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphResourceIdLayoutRoute:
      AppOrgSlugProjectSlugGraphResourceIdLayoutRouteWithChildren,
  }

const AppOrgSlugProjectSlugGraphLayoutRouteWithChildren =
  AppOrgSlugProjectSlugGraphLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugGraphLayoutRouteChildren,
  )

interface AppOrgSlugProjectSlugLayoutRouteChildren {
  AppOrgSlugProjectSlugGraphLayoutRoute: typeof AppOrgSlugProjectSlugGraphLayoutRouteWithChildren
  AppOrgSlugProjectSlugLogsRoute: typeof AppOrgSlugProjectSlugLogsRoute
  AppOrgSlugProjectSlugNetworkingRoute: typeof AppOrgSlugProjectSlugNetworkingRoute
  AppOrgSlugProjectSlugNewResourceRoute: typeof AppOrgSlugProjectSlugNewResourceRoute
  AppOrgSlugProjectSlugIndexRoute: typeof AppOrgSlugProjectSlugIndexRoute
}

const AppOrgSlugProjectSlugLayoutRouteChildren: AppOrgSlugProjectSlugLayoutRouteChildren =
  {
    AppOrgSlugProjectSlugGraphLayoutRoute:
      AppOrgSlugProjectSlugGraphLayoutRouteWithChildren,
    AppOrgSlugProjectSlugLogsRoute: AppOrgSlugProjectSlugLogsRoute,
    AppOrgSlugProjectSlugNetworkingRoute: AppOrgSlugProjectSlugNetworkingRoute,
    AppOrgSlugProjectSlugNewResourceRoute:
      AppOrgSlugProjectSlugNewResourceRoute,
    AppOrgSlugProjectSlugIndexRoute: AppOrgSlugProjectSlugIndexRoute,
  }

const AppOrgSlugProjectSlugLayoutRouteWithChildren =
  AppOrgSlugProjectSlugLayoutRoute._addFileChildren(
    AppOrgSlugProjectSlugLayoutRouteChildren,
  )

interface AppOrgSlugLayoutRouteChildren {
  AppOrgSlugProjectSlugLayoutRoute: typeof AppOrgSlugProjectSlugLayoutRouteWithChildren
  AppOrgSlugNetworkingRoute: typeof AppOrgSlugNetworkingRoute
  AppOrgSlugServersRoute: typeof AppOrgSlugServersRoute
  AppOrgSlugSettingsRoute: typeof AppOrgSlugSettingsRoute
  AppOrgSlugTeamRoute: typeof AppOrgSlugTeamRoute
  AppOrgSlugTerminalRoute: typeof AppOrgSlugTerminalRoute
  AppOrgSlugIndexRoute: typeof AppOrgSlugIndexRoute
}

const AppOrgSlugLayoutRouteChildren: AppOrgSlugLayoutRouteChildren = {
  AppOrgSlugProjectSlugLayoutRoute:
    AppOrgSlugProjectSlugLayoutRouteWithChildren,
  AppOrgSlugNetworkingRoute: AppOrgSlugNetworkingRoute,
  AppOrgSlugServersRoute: AppOrgSlugServersRoute,
  AppOrgSlugSettingsRoute: AppOrgSlugSettingsRoute,
  AppOrgSlugTeamRoute: AppOrgSlugTeamRoute,
  AppOrgSlugTerminalRoute: AppOrgSlugTerminalRoute,
  AppOrgSlugIndexRoute: AppOrgSlugIndexRoute,
}

const AppOrgSlugLayoutRouteWithChildren =
  AppOrgSlugLayoutRoute._addFileChildren(AppOrgSlugLayoutRouteChildren)

interface AppLayoutRouteChildren {
  AppOrgSlugLayoutRoute: typeof AppOrgSlugLayoutRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppOrgSlugLayoutRoute: AppOrgSlugLayoutRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  SignInRoute: SignInRoute,
  TerminalRoute: TerminalRoute,
  OnboardingCreateOrganizationRoute: OnboardingCreateOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
