// Helpers shared by the unified ProjectWorkspace bottom drawer.
// Originally ported as part of the standalone Stack/Console hero variants;
// extracted here so those screen files can be retired.

import { useEffect, useMemo, useState, type ReactNode } from "react";

import { EDGES, type Edge, type Service } from "../data";

// ───────── Stack-as-code TOML generator + line view ─────────

export function STACK_TOML(stack: Service[]): string {
  const lines: string[] = [];
  lines.push(`# helio.stack.toml — generated by Otterdeploy`);
  lines.push(`# edits here apply on save (⌘S). graph reflects in real time.`);
  lines.push(``);
  lines.push(`[project]`);
  lines.push(`name   = "helio"`);
  lines.push(`team   = "paperhouse"`);
  lines.push(`region = "sf-bay/rack-2"`);
  lines.push(``);
  for (const s of stack) {
    const head = s.kind === "database" ? "database" : "service";
    lines.push(`[[${head}]]`);
    lines.push(`name      = "${s.name}"`);
    if (s.repo) lines.push(`repo      = "${s.repo}"`);
    if (s.branch) lines.push(`branch    = "${s.branch}"`);
    if (s.image) lines.push(`image     = "${s.image}"`);
    if (s.port) lines.push(`port      = ${s.port}`);
    if (s.replicas != null) lines.push(`replicas  = ${s.replicas}`);
    if (s.domain) lines.push(`domain    = "${s.domain}"`);
    if (s.kind !== "database") {
      lines.push(`build     = { command = "pnpm build" }`);
      lines.push(`start     = { command = "pnpm start" }`);
    }
    lines.push(``);
  }
  lines.push(`[network]`);
  lines.push(`internal_dns = "*.helio.internal"`);
  lines.push(`edges = [`);
  for (const e of EDGES) {
    lines.push(`  { from = "${e.from}", to = "${e.to}", kind = "${e.kind}" },`);
  }
  lines.push(`]`);
  return lines.join("\n");
}

interface CodeLineProps {
  num: number;
  text: string;
  active: boolean;
  onHover: () => void;
  onLeave: () => void;
  onClick: () => void;
}

export function CodeLine({ num, text, active, onHover, onLeave, onClick }: CodeLineProps) {
  const tokens = highlightToml(text);
  return (
    <div
      onMouseEnter={onHover}
      onMouseLeave={onLeave}
      onClick={onClick}
      style={{
        display: "flex",
        padding: "0 16px",
        background: active ? "var(--bg-overlay)" : "transparent",
        borderLeft: `2px solid ${active ? "var(--fg)" : "transparent"}`,
        cursor: "pointer",
      }}
    >
      <span
        style={{
          width: 36,
          color: "var(--fg-4)",
          textAlign: "right",
          flex: "none",
          userSelect: "none",
          fontSize: 11,
        }}
      >
        {num}
      </span>
      <span style={{ paddingLeft: 14, whiteSpace: "pre" }}>{tokens}</span>
    </div>
  );
}

function highlightToml(line: string): ReactNode {
  if (!line.trim()) return " ";
  if (line.startsWith("#")) return <span style={{ color: "var(--fg-3)" }}>{line}</span>;
  const headMatch = line.match(/^(\[\[?[^\]]+\]?\])(.*)$/);
  if (headMatch) {
    return (
      <>
        <span style={{ color: "var(--fg)", fontWeight: 600 }}>{headMatch[1]}</span>
        <span>{headMatch[2]}</span>
      </>
    );
  }
  const kvMatch = line.match(/^(\s*)([a-z_]+)(\s*=\s*)(.*)$/);
  if (kvMatch) {
    const [, ind, k, eq, v] = kvMatch;
    let val: ReactNode;
    if (v!.startsWith('"')) val = <span style={{ color: "var(--info)" }}>{v}</span>;
    else if (/^-?\d/.test(v!)) val = <span style={{ color: "var(--ok)" }}>{v}</span>;
    else if (v!.startsWith("{") || v!.startsWith("[")) val = <span style={{ color: "var(--fg-2)" }}>{v}</span>;
    else val = <span>{v}</span>;
    return (
      <>
        {ind}
        <span style={{ color: "var(--fg)" }}>{k}</span>
        <span style={{ color: "var(--fg-3)" }}>{eq}</span>
        {val}
      </>
    );
  }
  if (line.includes("=") && line.includes('"')) {
    return (
      <span>
        {line.split(/("[^"]*")/).map((p, i) =>
          p.startsWith('"') ? (
            <span key={i} style={{ color: "var(--info)" }}>
              {p}
            </span>
          ) : (
            <span key={i}>{p}</span>
          ),
        )}
      </span>
    );
  }
  return line;
}

// ───────── Ops-console activity feed + edge traffic row ─────────

function Spark({ idx }: { idx: number }) {
  const sparkPath = useMemo(() => {
    const pts: number[] = [];
    let s = idx + 1;
    const rng = () => {
      s = (s * 9301 + 49297) % 233280;
      return s / 233280;
    };
    for (let i = 0; i < 30; i++) pts.push(50 + (rng() - 0.5) * 80);
    return pts.map((v, i) => `${i === 0 ? "M" : "L"} ${i * 4} ${20 - v * 0.18}`).join(" ");
  }, [idx]);
  return (
    <svg width="120" height="20" preserveAspectRatio="none" viewBox="0 0 120 20">
      <path d={sparkPath} fill="none" stroke="var(--fg-2)" strokeWidth="1" />
    </svg>
  );
}

export function EdgeRow({ e, idx, tick }: { e: Edge; idx: number; tick: number }) {
  const rps = Math.round(e.rps + Math.sin(tick + idx) * Math.min(20, e.rps * 0.1));
  const errPct = (Math.abs(Math.sin(tick * 0.7 + idx * 1.3)) * 0.4).toFixed(2);
  return (
    <div className="row" style={{ padding: "7px 14px", borderBottom: "1px solid var(--border)", fontSize: 12 }}>
      <span className="mono" style={{ width: 130, color: "var(--fg-2)" }}>{e.from}</span>
      <span className="mono" style={{ width: 16, color: "var(--fg-4)" }}>→</span>
      <span className="mono" style={{ width: 130, color: "var(--fg-2)" }}>{e.to}</span>
      <span className="mono" style={{ width: 80, color: "var(--fg-3)", fontSize: 11 }}>{e.kind}</span>
      <span style={{ flex: 1, paddingRight: 12 }}><Spark idx={idx} /></span>
      <span className="mono" style={{ width: 80, textAlign: "right" }}>{rps}</span>
      <span className="mono" style={{ width: 80, textAlign: "right", color: "var(--fg-3)" }}>
        {Math.round(40 + (idx + 1) * 12)}ms
      </span>
      <span
        className="mono"
        style={{
          width: 80,
          textAlign: "right",
          color: parseFloat(errPct) > 0.2 ? "var(--warn)" : "var(--fg-3)",
        }}
      >
        {errPct}%
      </span>
    </div>
  );
}

type ActivityKind = "deploy" | "health" | "log" | "env" | "scale";
interface ActivityItem {
  kind: ActivityKind;
  svc: string;
  msg: string;
  author: string;
  id: number | string;
  when: string;
  isNew?: boolean;
}

const ACTIVITY_TEMPLATES: Array<Omit<ActivityItem, "id" | "when">> = [
  { kind: "deploy", svc: "api", msg: "shipped 3f9b042", author: "arjun" },
  { kind: "health", svc: "worker", msg: "cpu > 70% on replica 2", author: "system" },
  { kind: "log", svc: "api", msg: "GET /v1/charges 201 184ms", author: "system" },
  { kind: "env", svc: "web", msg: "NEXT_PUBLIC_FEATURE_BANNER updated", author: "mira" },
  { kind: "scale", svc: "api", msg: "scaled up: 3 → 4 replicas", author: "autoscaler" },
  { kind: "log", svc: "web", msg: "ISR revalidated /pricing", author: "system" },
  { kind: "deploy", svc: "web", msg: "shipped 8a2c1f9", author: "mira" },
  { kind: "health", svc: "postgres", msg: "backup completed (18s)", author: "system" },
];

export function ActivityFeed({ tick }: { tick: number }) {
  const [items, setItems] = useState<ActivityItem[]>(() =>
    Array.from({ length: 12 }, (_, i) => ({
      ...ACTIVITY_TEMPLATES[i % ACTIVITY_TEMPLATES.length]!,
      id: i,
      when: `${i + 1}m`,
    })),
  );
  useEffect(() => {
    const t = ACTIVITY_TEMPLATES[Math.floor(Math.random() * ACTIVITY_TEMPLATES.length)]!;
    setItems((p) => [{ ...t, id: Math.random(), when: "now", isNew: true }, ...p.slice(0, 24)]);
  }, [tick]);

  const dot = (k: ActivityKind) =>
    k === "deploy"
      ? "var(--info)"
      : k === "health"
        ? "var(--warn)"
        : k === "scale"
          ? "var(--ok)"
          : "var(--fg-4)";

  return (
    <div className="col" style={{ gap: 1 }}>
      {items.map((a, i) => (
        <div
          key={a.id}
          className="row gap-2"
          style={{
            padding: "7px 8px",
            borderRadius: 4,
            fontSize: 12,
            background: a.isNew && i === 0 ? "var(--bg-overlay)" : "transparent",
            transition: "background 800ms",
          }}
        >
          <span
            style={{
              width: 5,
              height: 5,
              borderRadius: "50%",
              background: dot(a.kind),
              marginTop: 6,
              flex: "none",
            }}
          />
          <div style={{ flex: 1, minWidth: 0 }}>
            <div className="row gap-2">
              <span className="mono" style={{ fontWeight: 500 }}>{a.svc}</span>
              <span style={{ flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                {a.msg}
              </span>
            </div>
            <div style={{ fontSize: 11, color: "var(--fg-4)" }}>
              {a.author} · {a.when}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
