/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as ProjectLayoutRouteImport } from './routes/project/layout'
import { Route as AuthLayoutRouteImport } from './routes/auth/layout'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboard/layout'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as DashboardSwarmRouteImport } from './routes/_dashboard/swarm'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardServersRouteImport } from './routes/_dashboard/servers'
import { Route as DashboardRoutingRouteImport } from './routes/_dashboard/routing'
import { Route as DashboardRequestsRouteImport } from './routes/_dashboard/requests'
import { Route as DashboardMonitoringRouteImport } from './routes/_dashboard/monitoring'
import { Route as DashboardMembersRouteImport } from './routes/_dashboard/members'
import { Route as DashboardDockerRouteImport } from './routes/_dashboard/docker'
import { Route as DashboardActivityRouteImport } from './routes/_dashboard/activity'
import { Route as ProjectProjectIdLayoutRouteImport } from './routes/project/$projectId/layout'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectLayoutRoute = ProjectLayoutRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const DashboardSwarmRoute = DashboardSwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardRoutingRoute = DashboardRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardDockerRoute = DashboardDockerRouteImport.update({
  id: '/docker',
  path: '/docker',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const ProjectProjectIdLayoutRoute = ProjectProjectIdLayoutRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/auth': typeof AuthLayoutRouteWithChildren
  '/project': typeof ProjectLayoutRouteWithChildren
  '/containers': typeof ContainersRoute
  '/terminal': typeof TerminalRoute
  '/project/$projectId': typeof ProjectProjectIdLayoutRoute
  '/activity': typeof DashboardActivityRoute
  '/docker': typeof DashboardDockerRoute
  '/members': typeof DashboardMembersRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/requests': typeof DashboardRequestsRoute
  '/routing': typeof DashboardRoutingRoute
  '/servers': typeof DashboardServersRoute
  '/settings': typeof DashboardSettingsRoute
  '/swarm': typeof DashboardSwarmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthLayoutRouteWithChildren
  '/project': typeof ProjectLayoutRouteWithChildren
  '/containers': typeof ContainersRoute
  '/terminal': typeof TerminalRoute
  '/project/$projectId': typeof ProjectProjectIdLayoutRoute
  '/activity': typeof DashboardActivityRoute
  '/docker': typeof DashboardDockerRoute
  '/members': typeof DashboardMembersRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/requests': typeof DashboardRequestsRoute
  '/routing': typeof DashboardRoutingRoute
  '/servers': typeof DashboardServersRoute
  '/settings': typeof DashboardSettingsRoute
  '/swarm': typeof DashboardSwarmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth': typeof AuthLayoutRouteWithChildren
  '/project': typeof ProjectLayoutRouteWithChildren
  '/containers': typeof ContainersRoute
  '/terminal': typeof TerminalRoute
  '/project/$projectId': typeof ProjectProjectIdLayoutRoute
  '/_dashboard/activity': typeof DashboardActivityRoute
  '/_dashboard/docker': typeof DashboardDockerRoute
  '/_dashboard/members': typeof DashboardMembersRoute
  '/_dashboard/monitoring': typeof DashboardMonitoringRoute
  '/_dashboard/requests': typeof DashboardRequestsRoute
  '/_dashboard/routing': typeof DashboardRoutingRoute
  '/_dashboard/servers': typeof DashboardServersRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/swarm': typeof DashboardSwarmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/project'
    | '/containers'
    | '/terminal'
    | '/project/$projectId'
    | '/activity'
    | '/docker'
    | '/members'
    | '/monitoring'
    | '/requests'
    | '/routing'
    | '/servers'
    | '/settings'
    | '/swarm'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/project'
    | '/containers'
    | '/terminal'
    | '/project/$projectId'
    | '/activity'
    | '/docker'
    | '/members'
    | '/monitoring'
    | '/requests'
    | '/routing'
    | '/servers'
    | '/settings'
    | '/swarm'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/auth'
    | '/project'
    | '/containers'
    | '/terminal'
    | '/project/$projectId'
    | '/_dashboard/activity'
    | '/_dashboard/docker'
    | '/_dashboard/members'
    | '/_dashboard/monitoring'
    | '/_dashboard/requests'
    | '/_dashboard/routing'
    | '/_dashboard/servers'
    | '/_dashboard/settings'
    | '/_dashboard/swarm'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProjectLayoutRoute: typeof ProjectLayoutRouteWithChildren
  ContainersRoute: typeof ContainersRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_dashboard/swarm': {
      id: '/_dashboard/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof DashboardSwarmRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/servers': {
      id: '/_dashboard/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/routing': {
      id: '/_dashboard/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof DashboardRoutingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/requests': {
      id: '/_dashboard/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/monitoring': {
      id: '/_dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/members': {
      id: '/_dashboard/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/docker': {
      id: '/_dashboard/docker'
      path: '/docker'
      fullPath: '/docker'
      preLoaderRoute: typeof DashboardDockerRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboard/activity': {
      id: '/_dashboard/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdLayoutRouteImport
      parentRoute: typeof ProjectLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardDockerRoute: typeof DashboardDockerRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardRoutingRoute: typeof DashboardRoutingRoute
  DashboardServersRoute: typeof DashboardServersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSwarmRoute: typeof DashboardSwarmRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardDockerRoute: DashboardDockerRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardRoutingRoute: DashboardRoutingRoute,
  DashboardServersRoute: DashboardServersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSwarmRoute: DashboardSwarmRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface AuthLayoutRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProjectLayoutRouteChildren {
  ProjectProjectIdLayoutRoute: typeof ProjectProjectIdLayoutRoute
}

const ProjectLayoutRouteChildren: ProjectLayoutRouteChildren = {
  ProjectProjectIdLayoutRoute: ProjectProjectIdLayoutRoute,
}

const ProjectLayoutRouteWithChildren = ProjectLayoutRoute._addFileChildren(
  ProjectLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProjectLayoutRoute: ProjectLayoutRouteWithChildren,
  ContainersRoute: ContainersRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
