/**
 * GENERATED by brand/scripts/build_svgs.py: do not edit by hand.
 * Run `brand/scripts/build.sh` to regenerate.
 *
 * The mark's geometry, shared by the React component and the canvas favicon
 * renderer so the in-app mark and the browser-tab mark can never drift apart.
 */

/** What the counter inside the ring is saying. The ring itself never changes. */
export type MarkStatus = "idle" | "deploying" | "success" | "warning" | "error";

export const MARK_VIEW_BOX = "0 0 32 32";
export const MARK_GRID = 32;
export const MARK_STROKE = 2.6;
export const MARK_RING = { x: 4.6, y: 4.6, width: 22.8, height: 22.8, rx: 7.1 } as const;

/**
 * The travelling arc for `deploying`. `pathLength` normalises the rounded-rect
 * perimeter to 100, so the dash pattern is a percentage of the ring.
 */
export const MARK_ARC = {
  dashArray: "28 72",
  pathLength: 100,
  durationMs: 2200,
  /** Where the arc parks under `prefers-reduced-motion: reduce`. */
  staticOffset: -6,
} as const;

/** Stroked paths for each status's counter. A zero-length path is a round dot. */
export const MARK_GLYPHS: Record<MarkStatus, readonly string[]> = {
  idle: ["M10.6 21.4 21.4 10.6"],
  deploying: ["M10.6 21.4 21.4 10.6"],
  success: ["M11.2 16.4 14.8 20 21 12.8"],
  warning: ["M16 10.2 16 17", "M16 21.1 16 21.1"],
  error: ["M11.8 11.8 20.2 20.2", "M20.2 11.8 11.8 20.2"],
};

export const MARK_STATUS_COLORS: Record<MarkStatus, { light: string; dark: string }> = {
  idle: { light: "#1d4ed8", dark: "#3b82f6" },
  deploying: { light: "#1d4ed8", dark: "#3b82f6" },
  success: { light: "#1f7a3f", dark: "#4ade80" },
  warning: { light: "#8a6a00", dark: "#fbbf24" },
  error: { light: "#b42318", dark: "#f87171" },
};

/** The ring, in both themes. Warm ink, never pure black or white. */
export const MARK_INK = { light: "#141412", dark: "#f5f5f0" } as const;
