import type { SshKeyId } from "@otterdeploy/shared/id";

// SSH keys — org-scoped keypairs used to authenticate Git pulls (deploy keys)
// and to manage swarm nodes. Two flavours live in this one table:
//
//   - generated keys: we run `ssh-keygen`, store the PUBLIC half in the clear
//     (`publicKey`) and the PRIVATE half as AES-GCM ciphertext
//     (`privateKeyCiphertext`, via packages/api/src/lib/crypto). The private
//     key is never returned to the browser — only the public half + fingerprint.
//   - imported keys: the operator pastes a public key line; we keep only the
//     public half (`privateKeyCiphertext` is null). The private key lives on the
//     operator's machine, not ours.
//
// "Used by" (git providers / nodes / services consuming the key) is derived at
// read time from the subsystems that reference a key, not denormalized here —
// so this table never drifts out of sync with actual usage.
import { ID_PREFIX, createId } from "@otterdeploy/shared/id";
import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

import { organization } from "./auth";

export const sshKeyTypeEnum = pgEnum("ssh_key_type", ["ed25519", "rsa", "ecdsa"]);

export const sshKey = pgTable(
  "ssh_key",
  {
    id: text("id")
      .primaryKey()
      .$type<SshKeyId>()
      .$defaultFn(() => createId(ID_PREFIX.sshKey)),
    organizationId: text("organization_id")
      .notNull()
      .references(() => organization.id, { onDelete: "cascade" }),
    /** Operator-visible label, e.g. "otterdeploy-deploy". */
    name: text("name").notNull(),
    type: sshKeyTypeEnum("type").notNull(),
    /** Key size in bits — set for rsa/ecdsa, null for ed25519 (fixed-size). */
    bits: integer("bits"),
    /** Full OpenSSH public-key line: "ssh-ed25519 AAAA… comment". Not secret. */
    publicKey: text("public_key").notNull(),
    /** AES-GCM ciphertext of the OpenSSH private key. Null for imported
     *  (public-only) keys — we never hold their private half. */
    privateKeyCiphertext: text("private_key_ciphertext"),
    /** SHA256 fingerprint, e.g. "SHA256:Ad7Qm…". Unique per org (dedupes
     *  re-imports of the same key). */
    fingerprint: text("fingerprint").notNull(),
    /** Optional key comment (the trailing field of the public-key line). */
    comment: text("comment"),
    /** True when the public key was pasted in rather than generated by us. */
    imported: boolean("imported").notNull().default(false),
    /** Bumped by the subsystems that authenticate with this key. */
    lastUsedAt: timestamp("last_used_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (t) => [
    index("ssh_key_organization_id_idx").on(t.organizationId),
    // Same key can't be added twice within an org (by fingerprint).
    uniqueIndex("ssh_key_org_fingerprint_unique").on(t.organizationId, t.fingerprint),
  ],
);
