// Variation B — Stack as Code.
// Split view: visual graph on the left, declarative TOML on the right.
// Edits in either side reflect in the other (simulated). The selling point.

import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { I } from "../icons";
import { EDGES, SERVICES } from "../data";
import type { Env, Service } from "../data";

type Props = {
  env: Env;
  onOpenLogs: (id: string) => void;
  onDeploy: () => void;
  onOpenService: (id: string) => void;
  onNewService: () => void;
};

export function STACK_TOML(stack: Service[]): string {
  const lines: string[] = [];
  lines.push(`# helio.stack.toml — generated by Otterstack`);
  lines.push(`# edits here apply on save (⌘S). graph reflects in real time.`);
  lines.push(``);
  lines.push(`[project]`);
  lines.push(`name   = "helio"`);
  lines.push(`team   = "paperhouse"`);
  lines.push(`region = "sf-bay/rack-2"`);
  lines.push(``);
  for (const s of stack) {
    const head = s.kind === "database" ? "database" : "service";
    lines.push(`[[${head}]]`);
    lines.push(`name      = "${s.name}"`);
    if (s.repo) lines.push(`repo      = "${s.repo}"`);
    if (s.branch) lines.push(`branch    = "${s.branch}"`);
    if (s.image) lines.push(`image     = "${s.image}"`);
    if (s.port) lines.push(`port      = ${s.port}`);
    if (s.replicas != null) lines.push(`replicas  = ${s.replicas}`);
    if (s.domain) lines.push(`domain    = "${s.domain}"`);
    if (s.kind !== "database") {
      lines.push(`build     = { command = "pnpm build" }`);
      lines.push(`start     = { command = "pnpm start" }`);
    }
    lines.push(``);
  }
  lines.push(`[network]`);
  lines.push(`internal_dns = "*.helio.internal"`);
  lines.push(`edges = [`);
  for (const e of EDGES) {
    lines.push(`  { from = "${e.from}", to = "${e.to}", kind = "${e.kind}" },`);
  }
  lines.push(`]`);
  return lines.join("\n");
}

export function StackAsCode({ onDeploy }: Props) {
  const [stack] = useState<Service[]>(SERVICES);
  const [hoverLine, setHoverLine] = useState<number | null>(null);
  const [selectedNode, setSelectedNode] = useState<string>("api");
  const [dirty, setDirty] = useState(false);
  const [diff, setDiff] = useState(false);

  const toml = useMemo(() => STACK_TOML(stack), [stack]);
  const tomlLines = toml.split("\n");

  // Map line index → service id (rough heuristic: line containing `name = "X"`)
  const lineToService = useMemo(() => {
    const m: Record<number, string> = {};
    let cur: number | null = null;
    tomlLines.forEach((l, i) => {
      const headMatch = l.match(/^\[\[(service|database)\]\]/);
      if (headMatch) cur = i;
      const nameMatch = l.match(/^name\s+=\s+"([^"]+)"/);
      if (nameMatch && cur != null) {
        // tag this whole block
        let j = cur;
        while (j < tomlLines.length && (j === cur || !tomlLines[j].match(/^\[\[/))) {
          m[j] = nameMatch[1];
          j++;
          if (j < tomlLines.length && tomlLines[j].match(/^\[\[/)) break;
        }
      }
    });
    return m;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [toml]);

  return (
    <div style={{ flex: 1, display: "flex", overflow: "hidden" }}>
      {/* LEFT: minimap graph */}
      <div
        style={{
          width: "46%",
          position: "relative",
          overflow: "hidden",
          borderRight: "1px solid var(--border)",
          background: "var(--bg)",
          backgroundImage: "radial-gradient(circle at 1px 1px, var(--border) 1px, transparent 0)",
          backgroundSize: "20px 20px",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: 12,
            left: 12,
            right: 12,
            display: "flex",
            alignItems: "center",
            gap: 8,
            zIndex: 10,
          }}
        >
          <span className="badge">
            <I.graph width={10} height={10} /> visual
          </span>
          <div style={{ flex: 1 }} />
          <span className="muted" style={{ fontSize: 11 }}>
            both views are the source of truth
          </span>
        </div>

        <svg
          viewBox="0 0 880 560"
          style={{ position: "absolute", inset: 0, width: "100%", height: "100%" }}
          preserveAspectRatio="xMidYMid meet"
        >
          <defs>
            <marker id="arrow2" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto">
              <path d="M0,0 L8,4 L0,8 z" fill="var(--fg-3)" />
            </marker>
          </defs>
          {EDGES.map((e, i) => {
            const a = SERVICES.find((s) => s.id === e.from)!;
            const b = SERVICES.find((s) => s.id === e.to)!;
            const ax = a.pos.x + 60;
            const ay = a.pos.y + 30;
            const bx = b.pos.x;
            const by = b.pos.y + 30;
            const cx = (ax + bx) / 2;
            const path = `M ${ax} ${ay} C ${cx} ${ay}, ${cx} ${by}, ${bx} ${by}`;
            const highlit =
              selectedNode === e.from ||
              selectedNode === e.to ||
              (hoverLine !== null && (lineToService[hoverLine] === e.from || lineToService[hoverLine] === e.to));
            return (
              <path
                key={i}
                d={path}
                fill="none"
                stroke={highlit ? "var(--fg)" : "var(--border-strong)"}
                strokeWidth={highlit ? 1.6 : 1}
                markerEnd="url(#arrow2)"
                opacity={highlit ? 1 : 0.5}
              />
            );
          })}
          {SERVICES.map((n) => {
            const isHovered = hoverLine !== null && lineToService[hoverLine] === n.id;
            const isSelected = selectedNode === n.id;
            return (
              <g
                key={n.id}
                transform={`translate(${n.pos.x}, ${n.pos.y})`}
                onClick={() => setSelectedNode(n.id)}
                style={{ cursor: "pointer" }}
              >
                <rect
                  width="120"
                  height="60"
                  rx="8"
                  fill="var(--bg-elev)"
                  stroke={isSelected ? "var(--fg)" : isHovered ? "var(--fg-3)" : "var(--border)"}
                  strokeWidth={isSelected ? 1.5 : 1}
                />
                <rect
                  x="0"
                  y="0"
                  width="3"
                  height="60"
                  rx="1.5"
                  fill={
                    n.status === "healthy"
                      ? "var(--ok)"
                      : n.status === "degraded"
                        ? "var(--warn)"
                        : "var(--err)"
                  }
                />
                <text x="14" y="24" fontFamily="var(--font-mono)" fontSize="13" fontWeight="500" fill="var(--fg)">
                  {n.name}
                </text>
                <text x="14" y="40" fontFamily="var(--font-sans)" fontSize="10.5" fill="var(--fg-3)">
                  {n.kind === "database" ? n.image : `${n.replicas} × ${n.framework?.split(" ")[0] || "image"}`}
                </text>
              </g>
            );
          })}
        </svg>
      </div>

      {/* RIGHT: code editor */}
      <div
        style={{
          flex: 1,
          display: "flex",
          flexDirection: "column",
          overflow: "hidden",
          background: "var(--bg-elev)",
        }}
      >
        <div className="os-scroll" style={{ flex: 1, overflow: "auto" }}>
          {!diff ? (
            <div className="mono" style={{ fontSize: 12.5, lineHeight: 1.7, padding: "12px 0" }}>
              {tomlLines.map((line, i) => (
                <CodeLine
                  key={i}
                  num={i + 1}
                  text={line}
                  active={hoverLine === i || (lineToService[i] !== undefined && lineToService[i] === selectedNode)}
                  onHover={() => setHoverLine(i)}
                  onLeave={() => setHoverLine(null)}
                  onClick={() => {
                    if (lineToService[i]) {
                      setSelectedNode(lineToService[i]);
                      // mark dirty as a hint; not necessary for visual
                      if (!dirty) setDirty(false);
                    }
                  }}
                />
              ))}
            </div>
          ) : (
            <DiffView />
          )}
        </div>

        <div
          className="row gap-2"
          style={{
            padding: "8px 14px",
            borderTop: "1px solid var(--border)",
            background: "var(--bg-elev)",
          }}
        >
          <span className="badge mono" style={{ background: "var(--bg-sunken)" }}>
            helio.stack.toml
          </span>
          {dirty && (
            <span className="badge warn">
              <span className="dot" />
              unsaved
            </span>
          )}
          <div
            className="row gap-1"
            style={{
              marginLeft: 8,
              background: "var(--bg-sunken)",
              padding: 2,
              borderRadius: 5,
              border: "1px solid var(--border)",
            }}
          >
            <button
              onClick={() => setDiff(false)}
              className="mono"
              style={{
                padding: "3px 8px",
                fontSize: 11,
                borderRadius: 3,
                background: !diff ? "var(--bg-elev)" : "transparent",
                color: !diff ? "var(--fg)" : "var(--fg-3)",
                cursor: "pointer",
                boxShadow: !diff ? "var(--shadow-sm)" : "none",
              }}
            >
              edit
            </button>
            <button
              onClick={() => setDiff(true)}
              className="mono"
              style={{
                padding: "3px 8px",
                fontSize: 11,
                borderRadius: 3,
                background: diff ? "var(--bg-elev)" : "transparent",
                color: diff ? "var(--fg)" : "var(--fg-3)",
                cursor: "pointer",
                boxShadow: diff ? "var(--shadow-sm)" : "none",
              }}
            >
              diff vs prod
            </button>
          </div>
          <div style={{ flex: 1 }} />
          <span className="muted mono" style={{ fontSize: 11 }}>
            {tomlLines.length} lines
          </span>
          <button
            className="btn sm"
            onClick={() => setDirty(false)}
            disabled={!dirty}
            style={{ opacity: dirty ? 1 : 0.5 }}
          >
            Discard
          </button>
          <button className="btn primary sm" onClick={onDeploy}>
            <span className="mono" style={{ fontSize: 10 }}>
              ⌘S
            </span>{" "}
            Apply →
          </button>
        </div>
      </div>
    </div>
  );
}

type CodeLineProps = {
  num: number;
  text: string;
  active: boolean;
  onHover: () => void;
  onLeave: () => void;
  onClick: () => void;
};

export function CodeLine({ num, text, active, onHover, onLeave, onClick }: CodeLineProps) {
  // syntax highlight
  const tokens = highlightToml(text);
  return (
    <div
      onMouseEnter={onHover}
      onMouseLeave={onLeave}
      onClick={onClick}
      style={{
        display: "flex",
        padding: "0 16px",
        background: active ? "var(--bg-overlay)" : "transparent",
        borderLeft: `2px solid ${active ? "var(--fg)" : "transparent"}`,
        cursor: "pointer",
      }}
    >
      <span
        style={{
          width: 36,
          color: "var(--fg-4)",
          textAlign: "right",
          flex: "none",
          userSelect: "none",
          fontSize: 11,
        }}
      >
        {num}
      </span>
      <span style={{ paddingLeft: 14, whiteSpace: "pre" }}>{tokens}</span>
    </div>
  );
}

function highlightToml(line: string): ReactNode {
  if (!line.trim()) return " ";
  if (line.startsWith("#")) return <span style={{ color: "var(--fg-3)" }}>{line}</span>;
  const headMatch = line.match(/^(\[\[?[^\]]+\]?\])(.*)$/);
  if (headMatch) {
    return (
      <>
        <span style={{ color: "var(--fg)", fontWeight: 600 }}>{headMatch[1]}</span>
        <span>{headMatch[2]}</span>
      </>
    );
  }
  const kvMatch = line.match(/^(\s*)([a-z_]+)(\s*=\s*)(.*)$/);
  if (kvMatch) {
    const [, ind, k, eq, v] = kvMatch;
    let val: ReactNode;
    if (v.startsWith('"')) val = <span style={{ color: "var(--info)" }}>{v}</span>;
    else if (/^-?\d/.test(v)) val = <span style={{ color: "var(--ok)" }}>{v}</span>;
    else if (v.startsWith("{") || v.startsWith("[")) val = <span style={{ color: "var(--fg-2)" }}>{v}</span>;
    else val = <span>{v}</span>;
    return (
      <>
        {ind}
        <span style={{ color: "var(--fg)" }}>{k}</span>
        <span style={{ color: "var(--fg-3)" }}>{eq}</span>
        {val}
      </>
    );
  }
  // table values
  if (line.includes("=") && line.includes('"')) {
    return (
      <span>
        {line.split(/("[^"]*")/).map((p, i) =>
          p.startsWith('"') ? (
            <span key={i} style={{ color: "var(--info)" }}>
              {p}
            </span>
          ) : (
            <span key={i}>{p}</span>
          ),
        )}
      </span>
    );
  }
  return line;
}

function DiffView() {
  const lines: Array<{ t: " " | "+" | "-"; s: string }> = [
    { t: " ", s: "[[service]]" },
    { t: " ", s: 'name      = "api"' },
    { t: "-", s: "replicas  = 3" },
    { t: "+", s: "replicas  = 4" },
    { t: " ", s: "port      = 8080" },
    { t: " ", s: "" },
    { t: " ", s: "[[service]]" },
    { t: " ", s: 'name      = "worker"' },
    { t: "-", s: 'image     = "python:3.11-slim"' },
    { t: "+", s: 'image     = "python:3.12-slim"' },
    { t: " ", s: "" },
    { t: "+", s: "[[service]]" },
    { t: "+", s: 'name      = "imgproxy"' },
    { t: "+", s: 'image     = "darthsim/imgproxy:v3"' },
    { t: "+", s: "port      = 8081" },
    { t: "+", s: 'domain    = "img.helio.so"' },
  ];
  return (
    <div className="mono" style={{ fontSize: 12.5, lineHeight: 1.7, padding: 12 }}>
      <div
        className="row gap-2"
        style={{ padding: "0 16px 12px", borderBottom: "1px solid var(--border)", fontSize: 11 }}
      >
        <span className="muted">staging</span>
        <I.chev width={11} height={11} style={{ color: "var(--fg-3)" }} />
        <span className="muted">production</span>
        <div style={{ flex: 1 }} />
        <span style={{ color: "var(--ok)" }}>+5</span>
        <span style={{ color: "var(--err)" }}>−2</span>
      </div>
      {lines.map((l, i) => (
        <div
          key={i}
          style={{
            display: "flex",
            background: l.t === "+" ? "var(--ok-bg)" : l.t === "-" ? "var(--err-bg)" : "transparent",
            color: l.t === "+" ? "var(--ok)" : l.t === "-" ? "var(--err)" : "var(--fg-2)",
            padding: "0 16px",
          }}
        >
          <span style={{ width: 18, opacity: 0.7 }}>{l.t}</span>
          <span style={{ whiteSpace: "pre" }}>{l.s}</span>
        </div>
      ))}
    </div>
  );
}
